export type Course = {
  id: number;
  title: string;
  shortDescription?: string;
  description: string;
  image: string;
  rating: number;
  reviews: number;
  durationHours: number;
  price: number; // 0 = free
  totalVideos: number;
  instructorName: string;
  instructorImage: string;
  level?: string;
  category?: string;
  modules?: {
    id: number;
    title: string;
    lectures: number;
    duration?: string;
    topics?: {
      id: number;
      title: string;
      videoUrl?: string; // YouTube video URL
      resources?: { title: string; size?: string; file?: string }[];
    }[];
  }[];
  whatYouWillLearn?: string[];
  resources?: { title: string; size?: string; file?: string }[];
};

export const COURSES: Course[] = [
  {
    id: 21,
    title: 'Machine Learning with Python',
    shortDescription: 'Comprehensive ML course: supervised & unsupervised learning, neural networks, and real-world projects.',
    description: 'Master machine learning with Python using scikit-learn, TensorFlow, and PyTorch. Learn supervised and unsupervised learning, neural networks, deep learning, and deploy ML models. Build a portfolio with real-world projects including classification, regression, clustering, and computer vision applications.',
    image: '/Asset/ml.png',
    rating: 4.8,
    reviews: 1850,
    durationHours: 22,
    price: 50,
    totalVideos: 25,
    instructorName: 'Jashim Uddin',
    instructorImage: '/Asset/jashim uddin.jpg',
    level: 'Advanced',
    category: 'Data Science',
    modules: [
      {
        id: 1,
        title: 'ML Fundamentals',
        lectures: 5,
        duration: '5 hr',
        topics: [
          { id: 1, title: 'ML workflow', videoUrl: 'https://www.youtube.com/embed/ukzFI9rgwfU', resources: [{ title: 'ML overview', size: '200 KB', file: '/Asset/resources/ml/workflow.pdf' }] },
          { id: 2, title: 'Data preprocessing', videoUrl: 'https://www.youtube.com/embed/0xVqLJe9_CY', resources: [{ title: 'Preprocessing guide', size: '220 KB', file: '/Asset/resources/ml/preprocessing.pdf' }] },
          { id: 3, title: 'Feature engineering', videoUrl: 'https://www.youtube.com/embed/6WDFfaYtN6s', resources: [{ title: 'Feature engineering', size: '240 KB', file: '/Asset/resources/ml/features.pdf' }] },
          { id: 4, title: 'Model evaluation', videoUrl: 'https://www.youtube.com/embed/LbX4X71-TFI', resources: [{ title: 'Evaluation metrics', size: '180 KB', file: '/Asset/resources/ml/evaluation.pdf' }] },
          { id: 5, title: 'Cross-validation', videoUrl: 'https://www.youtube.com/embed/_Qd7YWSB1E8', resources: [{ title: 'Validation techniques', size: '160 KB', file: '/Asset/resources/ml/validation.pdf' }] },
        ],
      },
      {
        id: 2,
        title: 'Supervised Learning',
        lectures: 6,
        duration: '6 hr',
        topics: [
          { id: 1, title: 'Linear regression', videoUrl: 'https://www.youtube.com/embed/7ArmBVF2dCs', resources: [{ title: 'Regression guide', size: '190 KB', file: '/Asset/resources/ml/regression.pdf' }] },
          { id: 2, title: 'Logistic regression', videoUrl: 'https://www.youtube.com/embed/yIYKR4sgzI8', resources: [{ title: 'Logistic models', size: '180 KB', file: '/Asset/resources/ml/logistic.pdf' }] },
          { id: 3, title: 'Decision trees', videoUrl: 'https://www.youtube.com/embed/ZVR2Way4nwQ', resources: [{ title: 'Tree models', size: '200 KB', file: '/Asset/resources/ml/trees.pdf' }] },
          { id: 4, title: 'Random forests', videoUrl: 'https://www.youtube.com/embed/J4Wdy0Wc_xQ', resources: [{ title: 'Ensemble methods', size: '220 KB', file: '/Asset/resources/ml/forests.pdf' }] },
          { id: 5, title: 'Support Vector Machines', videoUrl: 'https://www.youtube.com/embed/_YPScrckx28', resources: [{ title: 'SVM guide', size: '210 KB', file: '/Asset/resources/ml/svm.pdf' }] },
          { id: 6, title: 'Gradient boosting', videoUrl: 'https://www.youtube.com/embed/3CC4N4z3GJc', resources: [{ title: 'Boosting algorithms', size: '230 KB', file: '/Asset/resources/ml/boosting.pdf' }] },
        ],
      },
      {
        id: 3,
        title: 'Unsupervised Learning',
        lectures: 5,
        duration: '4.5 hr',
        topics: [
          { id: 1, title: 'K-means clustering', videoUrl: 'https://www.youtube.com/embed/4b5d3muPQmA', resources: [{ title: 'Clustering basics', size: '180 KB', file: '/Asset/resources/ml/kmeans.pdf' }] },
          { id: 2, title: 'Hierarchical clustering', videoUrl: 'https://www.youtube.com/embed/7xHsRkOdVwo', resources: [{ title: 'Hierarchical methods', size: '190 KB', file: '/Asset/resources/ml/hierarchical.pdf' }] },
          { id: 3, title: 'DBSCAN', videoUrl: 'https://www.youtube.com/embed/RDZUdRSDOok', resources: [{ title: 'Density-based clustering', size: '170 KB', file: '/Asset/resources/ml/dbscan.pdf' }] },
          { id: 4, title: 'PCA & dimensionality reduction', videoUrl: 'https://www.youtube.com/embed/FgakZw6K1QQ', resources: [{ title: 'Dimensionality reduction', size: '200 KB', file: '/Asset/resources/ml/pca.pdf' }] },
          { id: 5, title: 'Anomaly detection', videoUrl: 'https://www.youtube.com/embed/H5ZQzl9eRJo', resources: [{ title: 'Anomaly detection', size: '180 KB', file: '/Asset/resources/ml/anomaly.pdf' }] },
        ],
      },
      {
        id: 4,
        title: 'Deep Learning',
        lectures: 6,
        duration: '6 hr',
        topics: [
          { id: 1, title: 'Neural networks basics', videoUrl: 'https://www.youtube.com/embed/aircAruvnKk', resources: [{ title: 'NN fundamentals', size: '220 KB', file: '/Asset/resources/ml/neural-nets.pdf' }] },
          { id: 2, title: 'TensorFlow & Keras', videoUrl: 'https://www.youtube.com/embed/tPYj3fFJGjk', resources: [{ title: 'TensorFlow guide', size: '250 KB', file: '/Asset/resources/ml/tensorflow.pdf' }] },
          { id: 3, title: 'CNNs for computer vision', videoUrl: 'https://www.youtube.com/embed/YRhxdVk_sIs', resources: [{ title: 'Convolutional networks', size: '240 KB', file: '/Asset/resources/ml/cnn.pdf' }] },
          { id: 4, title: 'RNNs & LSTMs', videoUrl: 'https://www.youtube.com/embed/LHXXI4-IEns', resources: [{ title: 'Recurrent networks', size: '230 KB', file: '/Asset/resources/ml/rnn.pdf' }] },
          { id: 5, title: 'Transfer learning', videoUrl: 'https://www.youtube.com/embed/yofjFQddwHE', resources: [{ title: 'Transfer learning', size: '210 KB', file: '/Asset/resources/ml/transfer.pdf' }] },
          { id: 6, title: 'Model deployment', videoUrl: 'https://www.youtube.com/embed/fw6NMQrYc6w', resources: [{ title: 'Deployment guide', size: '200 KB', file: '/Asset/resources/ml/deploy.pdf' }] },
        ],
      },
    ],
    whatYouWillLearn: [
      'Build supervised and unsupervised ML models',
      'Implement deep learning with TensorFlow',
      'Deploy machine learning models to production',
      'Work on real-world ML projects',
    ],
    resources: [
      { title: 'ML Project Notebooks', size: '8.5 MB', file: '/Asset/resources/ml-projects.zip' },
      { title: 'Datasets Collection', size: '12.3 MB', file: '/Asset/resources/ml-datasets.zip' },
    ],
  },
  {
    id: 20,
    title: 'C++ Modern Programming',
    shortDescription: 'Modern C++ (C++17/20): STL, templates, and performance. Build efficient, high-performance applications.',
    description: 'Master modern C++ with C++17 and C++20 features. Learn the Standard Template Library, templates, move semantics, smart pointers, and concurrency. Build high-performance applications with best practices and modern idioms.',
    image: '/Asset/cpp.png',
    rating: 4.5,
    reviews: 890,
    durationHours: 16,
    price: 40,
    totalVideos: 19,
    instructorName: 'Emily Rose',
    instructorImage: '/Asset/emily rose.jpg',
    level: 'Intermediate',
    category: 'Programming',
    modules: [
      {
        id: 1,
        title: 'C++ Fundamentals',
        lectures: 5,
        duration: '4.5 hr',
        topics: [
          { id: 1, title: 'Modern syntax', videoUrl: 'https://www.youtube.com/embed/vLnPwxZdW4Y', resources: [{ title: 'C++ syntax', size: '180 KB', file: '/Asset/resources/cpp/syntax.pdf' }] },
          { id: 2, title: 'References & pointers', videoUrl: 'https://www.youtube.com/embed/DTxHyVn0ODg', resources: [{ title: 'Pointers guide', size: '170 KB', file: '/Asset/resources/cpp/pointers.pdf' }] },
          { id: 3, title: 'Classes & OOP', videoUrl: 'https://www.youtube.com/embed/2BP8NhxjrO0', resources: [{ title: 'OOP in C++', size: '200 KB', file: '/Asset/resources/cpp/oop.pdf' }] },
          { id: 4, title: 'Constructors & RAII', videoUrl: 'https://www.youtube.com/embed/7Qgd9B1KuMQ', resources: [{ title: 'RAII pattern', size: '160 KB', file: '/Asset/resources/cpp/raii.pdf' }] },
          { id: 5, title: 'Operator overloading', videoUrl: 'https://www.youtube.com/embed/mS9755gF66w', resources: [{ title: 'Operators', size: '140 KB', file: '/Asset/resources/cpp/operators.pdf' }] },
        ],
      },
      {
        id: 2,
        title: 'Modern C++ Features',
        lectures: 5,
        duration: '5 hr',
        topics: [
          { id: 1, title: 'Smart pointers', videoUrl: 'https://www.youtube.com/embed/UOB7-B2MfwA', resources: [{ title: 'Smart pointers guide', size: '190 KB', file: '/Asset/resources/cpp/smart-pointers.pdf' }] },
          { id: 2, title: 'Move semantics', videoUrl: 'https://www.youtube.com/embed/St0MNEU5b0o', resources: [{ title: 'Move & rvalue', size: '200 KB', file: '/Asset/resources/cpp/move.pdf' }] },
          { id: 3, title: 'Lambda expressions', videoUrl: 'https://www.youtube.com/embed/MH8mLFqj-n8', resources: [{ title: 'Lambdas', size: '170 KB', file: '/Asset/resources/cpp/lambdas.pdf' }] },
          { id: 4, title: 'Templates', videoUrl: 'https://www.youtube.com/embed/I-hZkUa9mIs', resources: [{ title: 'Template guide', size: '210 KB', file: '/Asset/resources/cpp/templates.pdf' }] },
          { id: 5, title: 'C++17/20 features', videoUrl: 'https://www.youtube.com/embed/fI2xiUqqH3Q', resources: [{ title: 'Modern C++', size: '220 KB', file: '/Asset/resources/cpp/modern.pdf' }] },
        ],
      },
      {
        id: 3,
        title: 'STL & Performance',
        lectures: 5,
        duration: '4.5 hr',
        topics: [
          { id: 1, title: 'STL containers', videoUrl: 'https://www.youtube.com/embed/g-1Cn3ccwXY', resources: [{ title: 'Containers guide', size: '200 KB', file: '/Asset/resources/cpp/containers.pdf' }] },
          { id: 2, title: 'Algorithms', videoUrl: 'https://www.youtube.com/embed/2olsGf6JIkU', resources: [{ title: 'STL algorithms', size: '190 KB', file: '/Asset/resources/cpp/algorithms.pdf' }] },
          { id: 3, title: 'Iterators', videoUrl: 'https://www.youtube.com/embed/SgcHcbQ0RCQ', resources: [{ title: 'Iterator patterns', size: '160 KB', file: '/Asset/resources/cpp/iterators.pdf' }] },
          { id: 4, title: 'Concurrency', videoUrl: 'https://www.youtube.com/embed/F6Ipn7gCOsY', resources: [{ title: 'Threading', size: '200 KB', file: '/Asset/resources/cpp/concurrency.pdf' }] },
          { id: 5, title: 'Performance tuning', videoUrl: 'https://www.youtube.com/embed/NH1Tta7purM', resources: [{ title: 'Optimization', size: '180 KB', file: '/Asset/resources/cpp/performance.pdf' }] },
        ],
      },
    ],
    whatYouWillLearn: [
      'Write modern C++ code',
      'Master STL and templates',
      'Use smart pointers and move semantics',
      'Build high-performance applications',
    ],
    resources: [
      { title: 'C++ Code Examples', size: '2.5 MB', file: '/Asset/resources/cpp-examples.zip' },
    ],
  },
  {
    id: 19,
    title: 'Go Language',
    shortDescription: 'Learn Go for cloud-native apps, microservices, and concurrent systems. Build scalable backend services.',
    description: 'Master Go (Golang) for building modern cloud applications and microservices. Learn goroutines, channels, and Go\'s powerful standard library. Build REST APIs, gRPC services, and deploy to cloud platforms with best practices.',
    image: '/Asset/golang.png',
    rating: 3.7,
    reviews: 720,
    durationHours: 12,
    price: 38,
    totalVideos: 15,
    instructorName: 'Samira Khan',
    instructorImage: '/Asset/samira.jpg',
    level: 'Intermediate',
    category: 'Programming',
    modules: [
      {
        id: 1,
        title: 'Go Basics',
        lectures: 5,
        duration: '3.5 hr',
        topics: [
          { id: 1, title: 'Syntax & types', videoUrl: 'https://www.youtube.com/embed/YS4e4q9oBaU', resources: [{ title: 'Go syntax', size: '150 KB', file: '/Asset/resources/go/syntax.pdf' }] },
          { id: 2, title: 'Functions & methods', videoUrl: 'https://www.youtube.com/embed/15-XzWe1xGE', resources: [{ title: 'Functions guide', size: '160 KB', file: '/Asset/resources/go/functions.pdf' }] },
          { id: 3, title: 'Interfaces', videoUrl: 'https://www.youtube.com/embed/KB3ysH8cupY', resources: [{ title: 'Interfaces explained', size: '180 KB', file: '/Asset/resources/go/interfaces.pdf' }] },
          { id: 4, title: 'Error handling', videoUrl: 'https://www.youtube.com/embed/0T5VJTmMgGk', resources: [{ title: 'Error patterns', size: '140 KB', file: '/Asset/resources/go/errors.pdf' }] },
          { id: 5, title: 'Packages & modules', videoUrl: 'https://www.youtube.com/embed/mZ1pBMBMrRk', resources: [{ title: 'Module system', size: '130 KB', file: '/Asset/resources/go/modules.pdf' }] },
        ],
      },
      {
        id: 2,
        title: 'Concurrency in Go',
        lectures: 5,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'Goroutines', videoUrl: 'https://www.youtube.com/embed/oHIbeTmmTaA', resources: [{ title: 'Goroutines guide', size: '190 KB', file: '/Asset/resources/go/goroutines.pdf' }] },
          { id: 2, title: 'Channels', videoUrl: 'https://www.youtube.com/embed/KBZlN0izeiY', resources: [{ title: 'Channels patterns', size: '200 KB', file: '/Asset/resources/go/channels.pdf' }] },
          { id: 3, title: 'Select statement', videoUrl: 'https://www.youtube.com/embed/1c7ttSJDMAI', resources: [{ title: 'Select guide', size: '150 KB', file: '/Asset/resources/go/select.pdf' }] },
          { id: 4, title: 'Sync primitives', videoUrl: 'https://www.youtube.com/embed/eGC1LPc-9LI', resources: [{ title: 'Sync package', size: '170 KB', file: '/Asset/resources/go/sync.pdf' }] },
          { id: 5, title: 'Concurrency patterns', videoUrl: 'https://www.youtube.com/embed/5zXAHh5tJqQ', resources: [{ title: 'Go patterns', size: '180 KB', file: '/Asset/resources/go/patterns.pdf' }] },
        ],
      },
      {
        id: 3,
        title: 'Building Services',
        lectures: 5,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'HTTP servers', videoUrl: 'https://www.youtube.com/embed/jFfo23yIWac', resources: [{ title: 'HTTP in Go', size: '180 KB', file: '/Asset/resources/go/http.pdf' }] },
          { id: 2, title: 'REST APIs', videoUrl: 'https://www.youtube.com/embed/d_L64KT3SFM', resources: [{ title: 'REST guide', size: '190 KB', file: '/Asset/resources/go/rest.pdf' }] },
          { id: 3, title: 'gRPC services', videoUrl: 'https://www.youtube.com/embed/BdzYdN_Zd9Q', resources: [{ title: 'gRPC with Go', size: '210 KB', file: '/Asset/resources/go/grpc.pdf' }] },
          { id: 4, title: 'Database access', videoUrl: 'https://www.youtube.com/embed/p4JcQ14KgQE', resources: [{ title: 'Database guide', size: '170 KB', file: '/Asset/resources/go/database.pdf' }] },
          { id: 5, title: 'Testing & deployment', videoUrl: 'https://www.youtube.com/embed/8hQG7QlcLBk', resources: [{ title: 'Testing & deploy', size: '200 KB', file: '/Asset/resources/go/testing.pdf' }] },
        ],
      },
    ],
    whatYouWillLearn: [
      'Write concurrent programs with goroutines',
      'Build REST and gRPC services',
      'Deploy Go apps to cloud platforms',
      'Master Go best practices',
    ],
    resources: [
      { title: 'Go Service Templates', size: '2.1 MB', file: '/Asset/resources/go-templates.zip' },
    ],
  },
  {
    id: 18,
    title: 'Java Spring Boot Masterclass',
    shortDescription: 'Enterprise Java with Spring Boot: REST APIs, microservices, and Spring ecosystem. Production-ready apps.',
    description: 'Build enterprise-grade Java applications with Spring Boot. Learn dependency injection, Spring Data JPA, Spring Security, and microservices architecture. Deploy scalable applications with Docker and Kubernetes.',
    image: '/Asset/java spring.png',
    rating: 4.1,
    reviews: 1250,
    durationHours: 18,
    price: 42,
    totalVideos: 21,
    instructorName: 'Karan Sharma',
    instructorImage: '/Asset/karan.jpg',
    level: 'Intermediate',
    category: 'Programming',
    modules: [
      {
        id: 1,
        title: 'Spring Boot Fundamentals',
        lectures: 5,
        duration: '5 hr',
        topics: [
          { id: 1, title: 'Spring Boot intro', videoUrl: 'https://www.youtube.com/embed/9SGDpanrc8U', resources: [{ title: 'Boot overview', size: '180 KB', file: '/Asset/resources/java/spring-intro.pdf' }] },
          { id: 2, title: 'Dependency injection', videoUrl: 'https://www.youtube.com/embed/GB8k2-Egfv0', resources: [{ title: 'DI explained', size: '200 KB', file: '/Asset/resources/java/di.pdf' }] },
          { id: 3, title: 'Configuration', videoUrl: 'https://www.youtube.com/embed/lpcOSXWPXTk', resources: [{ title: 'App config', size: '160 KB', file: '/Asset/resources/java/config.pdf' }] },
          { id: 4, title: 'Spring MVC', videoUrl: 'https://www.youtube.com/embed/g2b-NbR48Jo', resources: [{ title: 'MVC guide', size: '190 KB', file: '/Asset/resources/java/mvc.pdf' }] },
          { id: 5, title: 'REST controllers', videoUrl: 'https://www.youtube.com/embed/vtPkZShrvXQ', resources: [{ title: 'REST APIs', size: '180 KB', file: '/Asset/resources/java/rest.pdf' }] },
        ],
      },
      {
        id: 2,
        title: 'Data & Persistence',
        lectures: 5,
        duration: '5 hr',
        topics: [
          { id: 1, title: 'Spring Data JPA', videoUrl: 'https://www.youtube.com/embed/8SGI_XS5OPw', resources: [{ title: 'JPA guide', size: '220 KB', file: '/Asset/resources/java/jpa.pdf' }] },
          { id: 2, title: 'Hibernate', videoUrl: 'https://www.youtube.com/embed/6TPDK6MOkz4', resources: [{ title: 'Hibernate basics', size: '200 KB', file: '/Asset/resources/java/hibernate.pdf' }] },
          { id: 3, title: 'Database migrations', videoUrl: 'https://www.youtube.com/embed/nFskii7Y9EY', resources: [{ title: 'Flyway guide', size: '150 KB', file: '/Asset/resources/java/migrations.pdf' }] },
          { id: 4, title: 'Transactions', videoUrl: 'https://www.youtube.com/embed/wrTGQWi-hus', resources: [{ title: 'Transaction management', size: '180 KB', file: '/Asset/resources/java/transactions.pdf' }] },
          { id: 5, title: 'Caching', videoUrl: 'https://www.youtube.com/embed/a_hzjkBZgMY', resources: [{ title: 'Spring Cache', size: '160 KB', file: '/Asset/resources/java/cache.pdf' }] },
        ],
      },
      {
        id: 3,
        title: 'Security & Microservices',
        lectures: 5,
        duration: '5 hr',
        topics: [
          { id: 1, title: 'Spring Security', videoUrl: 'https://www.youtube.com/embed/her_7pa0vrg', resources: [{ title: 'Security basics', size: '210 KB', file: '/Asset/resources/java/security.pdf' }] },
          { id: 2, title: 'JWT authentication', videoUrl: 'https://www.youtube.com/embed/X80nJ5T7YpE', resources: [{ title: 'JWT guide', size: '190 KB', file: '/Asset/resources/java/jwt.pdf' }] },
          { id: 3, title: 'Microservices patterns', videoUrl: 'https://www.youtube.com/embed/j1gU2oGFayY', resources: [{ title: 'Microservices', size: '220 KB', file: '/Asset/resources/java/microservices.pdf' }] },
          { id: 4, title: 'Spring Cloud', videoUrl: 'https://www.youtube.com/embed/WflS9MusV6g', resources: [{ title: 'Cloud features', size: '200 KB', file: '/Asset/resources/java/cloud.pdf' }] },
          { id: 5, title: 'Docker & K8s', videoUrl: 'https://www.youtube.com/embed/PH-2FfFD2PU', resources: [{ title: 'Deployment', size: '230 KB', file: '/Asset/resources/java/deploy.pdf' }] },
        ],
      },
    ],
    whatYouWillLearn: [
      'Build Spring Boot applications',
      'Implement REST APIs and microservices',
      'Secure apps with Spring Security',
      'Deploy with Docker and Kubernetes',
    ],
    resources: [
      { title: 'Spring Boot Projects', size: '4.5 MB', file: '/Asset/resources/spring-projects.zip' },
    ],
  },
  {
    id: 17,
    title: 'Rust Programming',
    shortDescription: 'Master Rust for systems programming, memory safety, and high-performance applications. Zero-cost abstractions and concurrency.',
    description: 'Learn Rust, the language for fearless systems programming. This course covers ownership, borrowing, lifetimes, and concurrent programming patterns. Build high-performance, memory-safe applications with hands-on projects including CLI tools, web servers, and systems utilities.',
    image: '/Asset/rust.png',
    rating: 2.8,
    reviews: 540,
    durationHours: 14,
    price: 45,
    totalVideos: 17,
    instructorName: 'Morgan Lee',
    instructorImage: '/Asset/morgan lee.jpg',
    level: 'Advanced',
    category: 'Programming',
    modules: [
      {
        id: 1,
        title: 'Rust Fundamentals',
        lectures: 5,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'Syntax & basics', videoUrl: 'https://www.youtube.com/embed/OX9HJsJUDxA', resources: [{ title: 'Rust syntax guide', size: '180 KB', file: '/Asset/resources/rust/syntax.pdf' }] },
          { id: 2, title: 'Ownership & borrowing', videoUrl: 'https://www.youtube.com/embed/VFIOSWy93H0', resources: [{ title: 'Ownership model', size: '200 KB', file: '/Asset/resources/rust/ownership.pdf' }] },
          { id: 3, title: 'Structs & enums', videoUrl: 'https://www.youtube.com/embed/67kciY4Cpxc', resources: [{ title: 'Data structures', size: '160 KB', file: '/Asset/resources/rust/structs.pdf' }] },
          { id: 4, title: 'Error handling', videoUrl: 'https://www.youtube.com/embed/wM6o70NAWUI', resources: [{ title: 'Result & Option', size: '140 KB', file: '/Asset/resources/rust/errors.pdf' }] },
          { id: 5, title: 'Pattern matching', videoUrl: 'https://www.youtube.com/embed/nqfgOJc-OAk', resources: [{ title: 'Pattern matching guide', size: '150 KB', file: '/Asset/resources/rust/patterns.pdf' }] },
        ],
      },
      {
        id: 2,
        title: 'Advanced Rust',
        lectures: 5,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'Lifetimes', videoUrl: 'https://www.youtube.com/embed/1QoT9fmPYr8', resources: [{ title: 'Lifetimes explained', size: '190 KB', file: '/Asset/resources/rust/lifetimes.pdf' }] },
          { id: 2, title: 'Traits & generics', videoUrl: 'https://www.youtube.com/embed/bnnacleqg6k', resources: [{ title: 'Traits system', size: '180 KB', file: '/Asset/resources/rust/traits.pdf' }] },
          { id: 3, title: 'Smart pointers', videoUrl: 'https://www.youtube.com/embed/CTTiaOo4cbY', resources: [{ title: 'Smart pointers guide', size: '170 KB', file: '/Asset/resources/rust/pointers.pdf' }] },
          { id: 4, title: 'Concurrency', videoUrl: 'https://www.youtube.com/embed/Dbytx0ivH7Q', resources: [{ title: 'Fearless concurrency', size: '200 KB', file: '/Asset/resources/rust/concurrency.pdf' }] },
          { id: 5, title: 'Unsafe Rust', videoUrl: 'https://www.youtube.com/embed/QAz-maaH0KM', resources: [{ title: 'Unsafe code', size: '160 KB', file: '/Asset/resources/rust/unsafe.pdf' }] },
        ],
      },
      {
        id: 3,
        title: 'Building with Rust',
        lectures: 4,
        duration: '3.5 hr',
        topics: [
          { id: 1, title: 'CLI applications', videoUrl: 'https://www.youtube.com/embed/MsocPEZBd-M', resources: [{ title: 'CLI tools', size: '180 KB', file: '/Asset/resources/rust/cli.pdf' }] },
          { id: 2, title: 'Web servers', videoUrl: 'https://www.youtube.com/embed/Dj6GkP0kQ0k', resources: [{ title: 'Web with Rust', size: '200 KB', file: '/Asset/resources/rust/web.pdf' }] },
          { id: 3, title: 'Testing & docs', videoUrl: 'https://www.youtube.com/embed/8XaVlL3lObQ', resources: [{ title: 'Testing guide', size: '140 KB', file: '/Asset/resources/rust/testing.pdf' }] },
          { id: 4, title: 'Performance tuning', videoUrl: 'https://www.youtube.com/embed/nlxGp-7b2dc', resources: [{ title: 'Optimization', size: '170 KB', file: '/Asset/resources/rust/performance.pdf' }] },
        ],
      },
    ],
    whatYouWillLearn: [
      'Master Rust ownership and borrowing',
      'Write safe concurrent programs',
      'Build high-performance systems',
      'Create CLI tools and web servers',
    ],
    resources: [
      { title: 'Rust Projects', size: '2.8 MB', file: '/Asset/resources/rust-projects.zip' },
    ],
  },
  {
    id: 16,
    title: 'TypeScript Complete Guide',
    shortDescription: 'Master TypeScript: types, generics, and advanced patterns. Build type-safe applications with confidence.',
    description: 'Learn TypeScript from basics to advanced type systems. Master type annotations, interfaces, generics, decorators, and advanced patterns. Build type-safe applications for frontend and backend with real-world projects.',
    image: '/Asset/typescript pro.png',
    rating: 3.9,
    reviews: 1560,
    durationHours: 10,
    price: 32,
    totalVideos: 14,
    instructorName: 'Morgan Lee',
    instructorImage: '/Asset/morgan lee.jpg',
    level: 'Intermediate',
    category: 'Programming',
    modules: [
      {
        id: 1,
        title: 'TypeScript Basics',
        lectures: 5,
        duration: '3 hr',
        topics: [
          { id: 1, title: 'Type annotations', videoUrl: 'https://www.youtube.com/embed/ahCwqrYpIuM', resources: [{ title: 'Types intro', size: '140 KB', file: '/Asset/resources/ts/types.pdf' }] },
          { id: 2, title: 'Interfaces', videoUrl: 'https://www.youtube.com/embed/VbW6vWTaHOY', resources: [{ title: 'Interfaces guide', size: '160 KB', file: '/Asset/resources/ts/interfaces.pdf' }] },
          { id: 3, title: 'Functions & types', videoUrl: 'https://www.youtube.com/embed/FhYJhRteY80', resources: [{ title: 'Function types', size: '150 KB', file: '/Asset/resources/ts/functions.pdf' }] },
          { id: 4, title: 'Union & intersection', videoUrl: 'https://www.youtube.com/embed/n3Yrqx9FNcQ', resources: [{ title: 'Type operators', size: '170 KB', file: '/Asset/resources/ts/operators.pdf' }] },
          { id: 5, title: 'Type guards', videoUrl: 'https://www.youtube.com/embed/sjITnlpQ7NQ', resources: [{ title: 'Guards & narrowing', size: '140 KB', file: '/Asset/resources/ts/guards.pdf' }] },
        ],
      },
      {
        id: 2,
        title: 'Advanced Types',
        lectures: 5,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'Generics', videoUrl: 'https://www.youtube.com/embed/nViEqpgwxHE', resources: [{ title: 'Generics guide', size: '190 KB', file: '/Asset/resources/ts/generics.pdf' }] },
          { id: 2, title: 'Utility types', videoUrl: 'https://www.youtube.com/embed/EU0TB_8KHpY', resources: [{ title: 'Utility types', size: '180 KB', file: '/Asset/resources/ts/utility.pdf' }] },
          { id: 3, title: 'Mapped types', videoUrl: 'https://www.youtube.com/embed/1VJdwUp3SVs', resources: [{ title: 'Mapped types', size: '170 KB', file: '/Asset/resources/ts/mapped.pdf' }] },
          { id: 4, title: 'Conditional types', videoUrl: 'https://www.youtube.com/embed/SbVgPQDealg', resources: [{ title: 'Conditional types', size: '200 KB', file: '/Asset/resources/ts/conditional.pdf' }] },
          { id: 5, title: 'Template literals', videoUrl: 'https://www.youtube.com/embed/NB2RN0yFEFQ', resources: [{ title: 'Template literal types', size: '160 KB', file: '/Asset/resources/ts/template-literals.pdf' }] },
        ],
      },
      {
        id: 3,
        title: 'TypeScript in Practice',
        lectures: 4,
        duration: '2.5 hr',
        topics: [
          { id: 1, title: 'Decorators', videoUrl: 'https://www.youtube.com/embed/O6A-u_FoEX8', resources: [{ title: 'Decorators guide', size: '170 KB', file: '/Asset/resources/ts/decorators.pdf' }] },
          { id: 2, title: 'TypeScript with React', videoUrl: 'https://www.youtube.com/embed/jrKcJxF0lAU', resources: [{ title: 'React + TS', size: '190 KB', file: '/Asset/resources/ts/react.pdf' }] },
          { id: 3, title: 'Node.js with TypeScript', videoUrl: 'https://www.youtube.com/embed/H91aqUHn8sE', resources: [{ title: 'Node + TS', size: '180 KB', file: '/Asset/resources/ts/node.pdf' }] },
          { id: 4, title: 'Build configuration', videoUrl: 'https://www.youtube.com/embed/xiDJz8eZhFk', resources: [{ title: 'TS config', size: '150 KB', file: '/Asset/resources/ts/config.pdf' }] },
        ],
      },
    ],
    whatYouWillLearn: [
      'Master TypeScript type system',
      'Use advanced type patterns',
      'Build type-safe applications',
      'Configure TypeScript projects',
    ],
    resources: [
      { title: 'TypeScript Projects', size: '1.8 MB', file: '/Asset/resources/ts-projects.zip' },
    ],
  },
  {
    id: 15,
    title: 'JavaScript ES6+ Deep Dive',
    shortDescription: 'Modern JavaScript mastery: ES6+, async patterns, and functional programming. Build robust applications.',
    description: 'Deep dive into modern JavaScript with ES6+ features, asynchronous programming, functional patterns, and performance optimization. Learn closures, prototypes, async/await, promises, and build production-ready applications.',
    image: '/Asset/java script.jpg',
    rating: 4.7,
    reviews: 2100,
    durationHours: 13,
    price: 28,
    totalVideos: 16,
    instructorName: 'Karim Kabir',
    instructorImage: '/Asset/karim.jpg',
    level: 'Intermediate',
    category: 'Programming',
    modules: [
      {
        id: 1,
        title: 'Modern JavaScript',
        lectures: 5,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'ES6+ syntax', videoUrl: 'https://www.youtube.com/embed/NCwa_xi0Uuc', resources: [{ title: 'ES6 features', size: '180 KB', file: '/Asset/resources/js/es6.pdf' }] },
          { id: 2, title: 'Arrow functions', videoUrl: 'https://www.youtube.com/embed/h33Srr5J9nY', resources: [{ title: 'Arrow functions', size: '140 KB', file: '/Asset/resources/js/arrows.pdf' }] },
          { id: 3, title: 'Destructuring', videoUrl: 'https://www.youtube.com/embed/NIq3qLaHCIs', resources: [{ title: 'Destructuring guide', size: '150 KB', file: '/Asset/resources/js/destructuring.pdf' }] },
          { id: 4, title: 'Spread & rest', videoUrl: 'https://www.youtube.com/embed/1INe_jCWq1Q', resources: [{ title: 'Spread operator', size: '130 KB', file: '/Asset/resources/js/spread.pdf' }] },
          { id: 5, title: 'Modules', videoUrl: 'https://www.youtube.com/embed/cRHQNNcYf6s', resources: [{ title: 'ES modules', size: '160 KB', file: '/Asset/resources/js/modules.pdf' }] },
        ],
      },
      {
        id: 2,
        title: 'Async JavaScript',
        lectures: 5,
        duration: '4.5 hr',
        topics: [
          { id: 1, title: 'Promises', videoUrl: 'https://www.youtube.com/embed/DHvZLI7Db8E', resources: [{ title: 'Promise guide', size: '190 KB', file: '/Asset/resources/js/promises.pdf' }] },
          { id: 2, title: 'Async/await', videoUrl: 'https://www.youtube.com/embed/V_Kr9OSfDeU', resources: [{ title: 'Async patterns', size: '200 KB', file: '/Asset/resources/js/async.pdf' }] },
          { id: 3, title: 'Event loop', videoUrl: 'https://www.youtube.com/embed/8aGhZQkoFbQ', resources: [{ title: 'Event loop explained', size: '180 KB', file: '/Asset/resources/js/event-loop.pdf' }] },
          { id: 4, title: 'Error handling', videoUrl: 'https://www.youtube.com/embed/cFTFtuEQ-10', resources: [{ title: 'Error handling', size: '150 KB', file: '/Asset/resources/js/error-handling.pdf' }] },
          { id: 5, title: 'Fetch & APIs', videoUrl: 'https://www.youtube.com/embed/cuEtnrL9-H0', resources: [{ title: 'API calls', size: '170 KB', file: '/Asset/resources/js/fetch.pdf' }] },
        ],
      },
      {
        id: 3,
        title: 'Advanced Concepts',
        lectures: 6,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'Closures', videoUrl: 'https://www.youtube.com/embed/3a0I8ICR1Vg', resources: [{ title: 'Closures deep dive', size: '170 KB', file: '/Asset/resources/js/closures.pdf' }] },
          { id: 2, title: 'Prototypes', videoUrl: 'https://www.youtube.com/embed/riDVvXZ_Kb4', resources: [{ title: 'Prototype chain', size: '180 KB', file: '/Asset/resources/js/prototypes.pdf' }] },
          { id: 3, title: 'This keyword', videoUrl: 'https://www.youtube.com/embed/gvicrj31JOM', resources: [{ title: 'This explained', size: '160 KB', file: '/Asset/resources/js/this.pdf' }] },
          { id: 4, title: 'Functional programming', videoUrl: 'https://www.youtube.com/embed/e-5obm1G_FY', resources: [{ title: 'FP patterns', size: '200 KB', file: '/Asset/resources/js/fp.pdf' }] },
          { id: 5, title: 'Iterators & generators', videoUrl: 'https://www.youtube.com/embed/IJ6EgdiI_wU', resources: [{ title: 'Iterators guide', size: '180 KB', file: '/Asset/resources/js/iterators.pdf' }] },
          { id: 6, title: 'Performance', videoUrl: 'https://www.youtube.com/embed/FQas7sDY2c8', resources: [{ title: 'JS optimization', size: '170 KB', file: '/Asset/resources/js/performance.pdf' }] },
        ],
      },
    ],
    whatYouWillLearn: [
      'Master modern JavaScript features',
      'Write asynchronous code effectively',
      'Understand closures and prototypes',
      'Apply functional programming patterns',
    ],
    resources: [
      { title: 'JS Advanced Examples', size: '2.0 MB', file: '/Asset/resources/js-advanced.zip' },
    ],
  },
  {
    id: 14,
    title: 'Database Design',
    shortDescription: 'Master database design patterns, normalization, and performance optimization. Learn indexing strategies and query tuning.',
    description: 'Take your database skills to the next level with advanced design patterns, normalization techniques, and performance optimization strategies. This course covers database design principles, indexing strategies, query optimization, and best practices for building scalable database systems. You will work with real-world scenarios and complex data models.',
    image: '/Asset/database design.jpg',
    rating: 4.5,
    reviews: 680,
    durationHours: 15,
    price: 35,
    totalVideos: 18,
    instructorName: 'Daniel Park',
    instructorImage: '/Asset/daniel.jpg',
    level: 'Advanced',
    category: 'Database',
    modules: [
      {
        id: 1,
        title: 'Database Design Principles',
        lectures: 5,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'Design patterns', videoUrl: 'https://www.youtube.com/embed/ztHopE5Wnpc', resources: [{ title: 'Design patterns guide', size: '200 KB', file: '/Asset/resources/db/design-patterns.pdf' }] },
          { id: 2, title: 'Normalization deep dive', videoUrl: 'https://www.youtube.com/embed/GFQaEYEc8_8', resources: [{ title: 'Normalization advanced', size: '180 KB', file: '/Asset/resources/db/normalization-advanced.pdf' }] },
          { id: 3, title: 'Denormalization strategies', videoUrl: 'https://www.youtube.com/embed/ScW5fJJP-fY', resources: [{ title: 'Denormalization guide', size: '150 KB', file: '/Asset/resources/db/denormalization.pdf' }] },
          { id: 4, title: 'Data integrity', videoUrl: 'https://www.youtube.com/embed/1D_h-yFtQVo', resources: [{ title: 'Integrity constraints', size: '120 KB', file: '/Asset/resources/db/integrity.pdf' }] },
          { id: 5, title: 'Schema evolution', videoUrl: 'https://www.youtube.com/embed/qMXs5n-BP_o', resources: [{ title: 'Schema migration', size: '140 KB', file: '/Asset/resources/db/schema-evolution.pdf' }] },
        ],
      },
      {
        id: 2,
        title: 'Query Optimization',
        lectures: 5,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'Query execution plans', videoUrl: 'https://www.youtube.com/embed/IwahVdNboc8', resources: [{ title: 'Execution plans', size: '180 KB', file: '/Asset/resources/db/execution-plans.pdf' }] },
          { id: 2, title: 'Index optimization', videoUrl: 'https://www.youtube.com/embed/fsG1XaZEa78', resources: [{ title: 'Index strategies', size: '200 KB', file: '/Asset/resources/db/index-optimization.pdf' }] },
          { id: 3, title: 'Query rewriting', videoUrl: 'https://www.youtube.com/embed/BHwzDmr6d7s', resources: [{ title: 'Query tuning', size: '150 KB', file: '/Asset/resources/db/query-rewriting.pdf' }] },
          { id: 4, title: 'Performance monitoring', videoUrl: 'https://www.youtube.com/embed/W-oWfI0Tqa0', resources: [{ title: 'Monitoring tools', size: '120 KB', file: '/Asset/resources/db/monitoring.pdf' }] },
          { id: 5, title: 'Caching strategies', videoUrl: 'https://www.youtube.com/embed/6FyXURRVmR0', resources: [{ title: 'Database caching', size: '160 KB', file: '/Asset/resources/db/caching.pdf' }] },
        ],
      },
      {
        id: 3,
        title: 'Scaling Databases',
        lectures: 4,
        duration: '3.5 hr',
        topics: [
          { id: 1, title: 'Sharding', videoUrl: 'https://www.youtube.com/embed/5faMjKuB9bc', resources: [{ title: 'Sharding guide', size: '190 KB', file: '/Asset/resources/db/sharding.pdf' }] },
          { id: 2, title: 'Replication strategies', videoUrl: 'https://www.youtube.com/embed/DQvmP9ho-2I', resources: [{ title: 'Replication patterns', size: '170 KB', file: '/Asset/resources/db/replication-advanced.pdf' }] },
          { id: 3, title: 'Load balancing', videoUrl: 'https://www.youtube.com/embed/K0Ta65OqQkY', resources: [{ title: 'Load balancing', size: '140 KB', file: '/Asset/resources/db/load-balancing.pdf' }] },
          { id: 4, title: 'Partitioning', videoUrl: 'https://www.youtube.com/embed/QA25cMWp9Tk', resources: [{ title: 'Partitioning strategies', size: '150 KB', file: '/Asset/resources/db/partitioning.pdf' }] },
        ],
      },
      {
        id: 4,
        title: 'Database Security',
        lectures: 4,
        duration: '3 hr',
        topics: [
          { id: 1, title: 'Access control', videoUrl: 'https://www.youtube.com/embed/71qk-qLFOsk', resources: [{ title: 'Access control guide', size: '130 KB', file: '/Asset/resources/db/access-control.pdf' }] },
          { id: 2, title: 'Encryption', videoUrl: 'https://www.youtube.com/embed/C4ATDMIz5wc', resources: [{ title: 'Data encryption', size: '150 KB', file: '/Asset/resources/db/encryption.pdf' }] },
          { id: 3, title: 'Audit logging', videoUrl: 'https://www.youtube.com/embed/SmfR8mCHQBk', resources: [{ title: 'Audit logs', size: '120 KB', file: '/Asset/resources/db/audit-logging.pdf' }] },
          { id: 4, title: 'Backup & recovery', videoUrl: 'https://www.youtube.com/embed/S7ApMHfgD7Y', resources: [{ title: 'Backup strategies', size: '180 KB', file: '/Asset/resources/db/backup-recovery.pdf' }] },
        ],
      },
    ],
    whatYouWillLearn: [
      'Design scalable database schemas',
      'Optimize complex queries and indexes',
      'Implement sharding and replication',
      'Secure and monitor database systems',
    ],
    resources: [
      { title: 'Advanced DB Scripts', size: '2.5 MB', file: '/Asset/resources/advanced-db.zip' },
      { title: 'Performance Toolkit', size: '1.8 MB', file: '/Asset/resources/db-performance.zip' },
    ],
  },
  {
    id: 13,
    title: 'PostgreSQL Mastery',
    shortDescription: 'Complete PostgreSQL course: from basics to advanced features. Learn JSONB, full-text search, and extensions.',
    description: 'Master PostgreSQL from fundamentals to advanced features. This comprehensive course covers everything from basic SQL to advanced PostgreSQL-specific features like JSONB, full-text search, window functions, and custom extensions. Learn to build robust, high-performance applications with PostgreSQL.',
    image: '/Asset/postgre.png',
    rating: 2.9,
    reviews: 820,
    durationHours: 20,
    price: 40,
    totalVideos: 22,
    instructorName: 'Rohan Patel',
    instructorImage: '/Asset/rohan patel.jpg',
    level: 'Intermediate',
    category: 'Database',
    modules: [
      {
        id: 1,
        title: 'PostgreSQL Fundamentals',
        lectures: 5,
        duration: '5 hr',
        topics: [
          { id: 1, title: 'Installation & setup', videoUrl: 'https://www.youtube.com/embed/qw--VYLpxG4', resources: [{ title: 'Setup guide', size: '150 KB', file: '/Asset/resources/postgres/setup.pdf' }] },
          { id: 2, title: 'Basic SQL operations', videoUrl: 'https://www.youtube.com/embed/jNq5EAb2biY', resources: [{ title: 'SQL basics', size: '180 KB', file: '/Asset/resources/postgres/sql-basics.pdf' }] },
          { id: 3, title: 'Data types', videoUrl: 'https://www.youtube.com/embed/4Z9KEBexzcM', resources: [{ title: 'PostgreSQL types', size: '200 KB', file: '/Asset/resources/postgres/data-types.pdf' }] },
          { id: 4, title: 'Constraints & keys', videoUrl: 'https://www.youtube.com/embed/7F5K8YzaNl4', resources: [{ title: 'Constraints guide', size: '140 KB', file: '/Asset/resources/postgres/constraints.pdf' }] },
          { id: 5, title: 'Table design', videoUrl: 'https://www.youtube.com/embed/h0j0QN2b57M', resources: [{ title: 'Table design patterns', size: '160 KB', file: '/Asset/resources/postgres/table-design.pdf' }] },
        ],
      },
      {
        id: 2,
        title: 'Advanced Queries',
        lectures: 5,
        duration: '5 hr',
        topics: [
          { id: 1, title: 'Window functions', videoUrl: 'https://www.youtube.com/embed/Ww71knvhQ-s', resources: [{ title: 'Window functions guide', size: '220 KB', file: '/Asset/resources/postgres/window-functions.pdf' }] },
          { id: 2, title: 'CTEs & subqueries', videoUrl: 'https://www.youtube.com/embed/Fb2oGpVLChw', resources: [{ title: 'CTEs tutorial', size: '180 KB', file: '/Asset/resources/postgres/ctes.pdf' }] },
          { id: 3, title: 'Array operations', videoUrl: 'https://www.youtube.com/embed/dLdZ94D0DyI', resources: [{ title: 'Array handling', size: '150 KB', file: '/Asset/resources/postgres/arrays.pdf' }] },
          { id: 4, title: 'JSON & JSONB', videoUrl: 'https://www.youtube.com/embed/1DplBw8CYX0', resources: [{ title: 'JSON in PostgreSQL', size: '200 KB', file: '/Asset/resources/postgres/json.pdf' }] },
          { id: 5, title: 'Full-text search', videoUrl: 'https://www.youtube.com/embed/szfUbzsKvEE', resources: [{ title: 'Text search guide', size: '190 KB', file: '/Asset/resources/postgres/full-text-search.pdf' }] },
        ],
      },
      {
        id: 3,
        title: 'Performance & Indexes',
        lectures: 5,
        duration: '5 hr',
        topics: [
          { id: 1, title: 'Index types', videoUrl: 'https://www.youtube.com/embed/fsG1XaZEa78', resources: [{ title: 'Index types guide', size: '180 KB', file: '/Asset/resources/postgres/index-types.pdf' }] },
          { id: 2, title: 'EXPLAIN & ANALYZE', videoUrl: 'https://www.youtube.com/embed/IwahVdNboc8', resources: [{ title: 'Query analysis', size: '200 KB', file: '/Asset/resources/postgres/explain.pdf' }] },
          { id: 3, title: 'Vacuum & maintenance', videoUrl: 'https://www.youtube.com/embed/eDdkSw5p70A', resources: [{ title: 'Maintenance guide', size: '160 KB', file: '/Asset/resources/postgres/vacuum.pdf' }] },
          { id: 4, title: 'Partitioning tables', videoUrl: 'https://www.youtube.com/embed/3OYhIwZWzjE', resources: [{ title: 'Table partitioning', size: '190 KB', file: '/Asset/resources/postgres/partitioning.pdf' }] },
          { id: 5, title: 'Connection pooling', videoUrl: 'https://www.youtube.com/embed/f34OZWcuSjU', resources: [{ title: 'Connection pools', size: '140 KB', file: '/Asset/resources/postgres/pooling.pdf' }] },
        ],
      },
      {
        id: 4,
        title: 'Advanced Features',
        lectures: 5,
        duration: '5 hr',
        topics: [
          { id: 1, title: 'Stored procedures', videoUrl: 'https://www.youtube.com/embed/6Sx6oEIgn_M', resources: [{ title: 'Procedures guide', size: '170 KB', file: '/Asset/resources/postgres/procedures.pdf' }] },
          { id: 2, title: 'Triggers & rules', videoUrl: 'https://www.youtube.com/embed/M2wVgj-6yoY', resources: [{ title: 'Triggers tutorial', size: '180 KB', file: '/Asset/resources/postgres/triggers.pdf' }] },
          { id: 3, title: 'Extensions', videoUrl: 'https://www.youtube.com/embed/GEqYmVs7Vy0', resources: [{ title: 'PostgreSQL extensions', size: '200 KB', file: '/Asset/resources/postgres/extensions.pdf' }] },
          { id: 4, title: 'Replication setup', videoUrl: 'https://www.youtube.com/embed/DNvEGfn_7Ls', resources: [{ title: 'Replication guide', size: '220 KB', file: '/Asset/resources/postgres/replication.pdf' }] },
          { id: 5, title: 'Backup strategies', videoUrl: 'https://www.youtube.com/embed/anCfz-S4eTI', resources: [{ title: 'Backup & restore', size: '190 KB', file: '/Asset/resources/postgres/backup.pdf' }] },
        ],
      },
    ],
    whatYouWillLearn: [
      'Master PostgreSQL from basics to advanced',
      'Use JSONB and full-text search effectively',
      'Optimize queries with proper indexing',
      'Implement replication and high availability',
    ],
    resources: [
      { title: 'PostgreSQL Cheatsheet', size: '1.5 MB', file: '/Asset/resources/postgres-cheatsheet.pdf' },
      { title: 'Sample Databases', size: '3.2 MB', file: '/Asset/resources/postgres-samples.zip' },
    ],
  },
  {
    id: 12,
    title: 'Complete Software Testing Mastery',
  shortDescription: 'Master manual & automated testing with hands-on examples. Gain practical skills through labs and sample projects.',
    description: 'Master both manual and automated testing with real-world examples and hands-on practice.This course guides you through writing effective test cases, automating web UI tests with Selenium, testing APIs with Postman, and integrating tests into CI pipelines. Includes practical labs, downloadable resources, and sample projects to help you build a testing portfolio.',
    image: '/Asset/software test.jpg',
    rating: 4.6,
    reviews: 950,
    durationHours: 16,
    price: 20,
    totalVideos: 19,
    instructorName: 'Kate Weber',
    instructorImage: '/Asset/Kate weber.png',
    level: 'Intermediate',
    category: 'Software Testing',
    modules: [
      {
        id: 1,
        title: 'Introduction to Testing',
        lectures: 4,
        duration: '1.5 hr',
        topics: [
          { id: 1, title: 'What is testing?', videoUrl: 'https://www.youtube.com/embed/u6QfIXgjwGQ', resources: [{ title: 'Intro slides', size: '200 KB', file: '/Asset/resources/testing/intro-slides.pdf' }] },
          { id: 2, title: 'Testing terminology', videoUrl: 'https://www.youtube.com/embed/E2bjmGvByKw', resources: [{ title: 'Glossary', size: '120 KB', file: '/Asset/resources/testing/glossary.pdf' }] },
          { id: 3, title: 'Testing lifecycle', videoUrl: 'https://www.youtube.com/embed/Y3SXeMx51mw', resources: [{ title: 'Lifecycle diagram', size: '300 KB', file: '/Asset/resources/testing/lifecycle.pdf' }] },
          { id: 4, title: 'Tools overview', videoUrl: 'https://www.youtube.com/embed/ydddSkVz_a8', resources: [{ title: 'Tools list', size: '150 KB', file: '/Asset/resources/testing/tools.pdf' }] },
        ],
      },
      {
        id: 2,
        title: 'Manual Testing Techniques',
        lectures: 5,
        duration: '3 hr',
        topics: [
          { id: 1, title: 'Test case design', videoUrl: 'https://www.youtube.com/embed/6q7LjyGaZcY', resources: [{ title: 'Test case template', size: '80 KB', file: '/Asset/resources/testing/testcase.docx' }] },
          { id: 2, title: 'Exploratory testing', videoUrl: 'https://www.youtube.com/embed/0LqmI6BFySA', resources: [{ title: 'Exploratory checklist', size: '60 KB', file: '/Asset/resources/testing/exploratory.pdf' }] },
          { id: 3, title: 'Bug reporting', videoUrl: 'https://www.youtube.com/embed/dsranEbAJhE', resources: [{ title: 'Bug report sample', size: '90 KB', file: '/Asset/resources/testing/bug-report.pdf' }] },
          { id: 4, title: 'Session-based testing', videoUrl: 'https://www.youtube.com/embed/u7z9Qw7b4Rw', resources: [{ title: 'Session templates', size: '70 KB', file: '/Asset/resources/testing/session-templates.zip' }] },
          { id: 5, title: 'Acceptance criteria', videoUrl: 'https://www.youtube.com/embed/zzagKrS0Cq8', resources: [{ title: 'AC examples', size: '50 KB', file: '/Asset/resources/testing/ac-examples.pdf' }] },
        ],
      },
      {
        id: 3,
        title: 'Automation with Selenium',
        lectures: 6,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'Selenium basics', videoUrl: 'https://www.youtube.com/embed/Xjv1sY630Uc', resources: [{ title: 'Selenium guide', size: '1.2 MB', file: '/Asset/resources/testing/selenium-guide.pdf' }] },
          { id: 2, title: 'Selectors and waits', videoUrl: 'https://www.youtube.com/embed/LH2eyXRRQR4', resources: [{ title: 'Selectors cheatsheet', size: '200 KB', file: '/Asset/resources/testing/selectors.pdf' }] },
          { id: 3, title: 'Page object model', videoUrl: 'https://www.youtube.com/embed/8Xd0unpsYN0', resources: [{ title: 'PO pattern', size: '300 KB', file: '/Asset/resources/testing/po-pattern.pdf' }] },
          { id: 4, title: 'CI integration', videoUrl: 'https://www.youtube.com/embed/v12BoGmtVNQ', resources: [{ title: 'CI guide', size: '400 KB', file: '/Asset/resources/testing/ci-guide.pdf' }] },
          { id: 5, title: 'Best practices', videoUrl: 'https://www.youtube.com/embed/6y-a5d5rihw', resources: [{ title: 'Automation best practices', size: '150 KB', file: '/Asset/resources/testing/automation-best.pdf' }] },
          { id: 6, title: 'Flaky tests', videoUrl: 'https://www.youtube.com/embed/lTSwd8r-igo', resources: [{ title: 'Flaky tests', size: '180 KB', file: '/Asset/resources/testing/flaky-tests.pdf' }] },
        ],
      },
      {
        id: 4,
        title: 'API Testing & Postman',
        lectures: 4,
        duration: '2 hr',
        topics: [
          { id: 1, title: 'HTTP basics', videoUrl: 'https://www.youtube.com/embed/iYM2zFP3Zn0', resources: [{ title: 'HTTP cheat sheet', size: '90 KB', file: '/Asset/resources/testing/http.pdf' }] },
          { id: 2, title: 'Postman collections', videoUrl: 'https://www.youtube.com/embed/VywxIQ2ZXw4', resources: [{ title: 'Postman collection', size: '500 KB', file: '/Asset/resources/testing/postman-collection.json' }] },
          { id: 3, title: 'API assertions', videoUrl: 'https://www.youtube.com/embed/M0JCdAqUMK4', resources: [{ title: 'Assertion examples', size: '120 KB', file: '/Asset/resources/testing/api-assertions.pdf' }] },
          { id: 4, title: 'Mocking APIs', videoUrl: 'https://www.youtube.com/embed/zjBpXw8xFsM', resources: [{ title: 'Mocking guide', size: '80 KB', file: '/Asset/resources/testing/mocking.pdf' }] },
        ],
      },
    ],
    whatYouWillLearn: [
      'Write effective manual test cases',
      'Automate web UI tests with Selenium',
      'Use Postman for API testing',
      'Integrate tests into CI pipelines',
    ],
    resources: [
      { title: 'Course Slides', size: '2.1 MB', file: '/Asset/resources/testing-slides.pdf' },
      { title: 'Sample Test Cases', size: '800 KB', file: '/Asset/resources/testing-cases.pdf' },
    ],
  },
  {
    id: 11,
    title: 'Node.js APIs and Microservices',
  shortDescription: 'Build scalable Node APIs and microservices. Includes hands-on projects for observability and deployment.',
    description: 'Build scalable APIs with Node, Express and microservice patterns. Learn how to design RESTful services, integrate databases, and apply microservice communication patterns. Hands-on projects teach testing, observability, and deployment practices for production-ready services.',
    image: '/Asset/nodejs.jpg',
    rating: 3.3,
    reviews: 480,
    durationHours: 14,
    price: 29,
    totalVideos: 18,
    instructorName: 'Samira Khan',
    instructorImage: '/Asset/samira.jpg',
    level: 'Advanced',
    category: 'Web Development',
    modules: [
      { id: 1,
        title: 'Node.js Fundamentals',
        lectures: 4,
        duration: '2 hr',
        topics: [
          { id: 1, title: 'Runtime & modules', videoUrl: 'https://www.youtube.com/embed/TlB_eWDSMt4', resources: [{ title: 'Node overview', size: '200 KB', file: '/Asset/resources/node/runtime.pdf' }] },
          { id: 2, title: 'Event loop', videoUrl: 'https://www.youtube.com/embed/8aGhZQkoFbQ', resources: [{ title: 'Event loop explainer', size: '150 KB', file: '/Asset/resources/node/event-loop.pdf' }] },
          { id: 3, title: 'Streams', videoUrl: 'https://www.youtube.com/embed/GlybFFMXXmQ', resources: [{ title: 'Streams guide', size: '180 KB', file: '/Asset/resources/node/streams.pdf' }] },
          { id: 4, title: 'Buffers', videoUrl: 'https://www.youtube.com/embed/8QBO5KVOiUQ', resources: [{ title: 'Buffers notes', size: '90 KB', file: '/Asset/resources/node/buffers.pdf' }] },
        ] },
      { id: 2,
        title: 'Express & Routing',
        lectures: 5,
        duration: '3 hr',
        topics: [
          { id: 1, title: 'Routing basics', videoUrl: 'https://www.youtube.com/embed/SccSCuHhOw0', resources: [{ title: 'Routing cheatsheet', size: '80 KB', file: '/Asset/resources/node/routing.pdf' }] },
          { id: 2, title: 'Middleware', videoUrl: 'https://www.youtube.com/embed/lY6icfhap2o', resources: [{ title: 'Middleware patterns', size: '120 KB', file: '/Asset/resources/node/middleware.pdf' }] },
          { id: 3, title: 'Error handling', videoUrl: 'https://www.youtube.com/embed/w2o51KU7rrM', resources: [{ title: 'Error handling', size: '70 KB', file: '/Asset/resources/node/errors.pdf' }] },
          { id: 4, title: 'Security', videoUrl: 'https://www.youtube.com/embed/F7NVpxxmmgM', resources: [{ title: 'Security checklist', size: '140 KB', file: '/Asset/resources/node/security.pdf' }] },
          { id: 5, title: 'Testing APIs', videoUrl: 'https://www.youtube.com/embed/FKnzS_icp20', resources: [{ title: 'API testing guide', size: '200 KB', file: '/Asset/resources/node/api-testing.pdf' }] },
        ] },
      { id: 3,
        title: 'Databases & ORMs',
        lectures: 5,
        duration: '3.5 hr',
        topics: [
          { id: 1, title: 'SQL vs NoSQL', videoUrl: 'https://www.youtube.com/embed/ruz-vK8IesE', resources: [{ title: 'DB comparison', size: '120 KB', file: '/Asset/resources/node/db-compare.pdf' }] },
          { id: 2, title: 'Using ORM', videoUrl: 'https://www.youtube.com/embed/dHQ-I7kr_SY', resources: [{ title: 'ORM cheatsheet', size: '200 KB', file: '/Asset/resources/node/orm.pdf' }] },
          { id: 3, title: 'Migrations', videoUrl: 'https://www.youtube.com/embed/qsDvJrGMSUY', resources: [{ title: 'Migration guide', size: '90 KB', file: '/Asset/resources/node/migrations.pdf' }] },
          { id: 4, title: 'Indexing', videoUrl: 'https://www.youtube.com/embed/fsG1XaZEa78', resources: [{ title: 'Indexing notes', size: '80 KB', file: '/Asset/resources/node/indexing.pdf' }] },
          { id: 5, title: 'Replication', videoUrl: 'https://www.youtube.com/embed/DQvmP9ho-2I', resources: [{ title: 'Replication primer', size: '110 KB', file: '/Asset/resources/node/replication.pdf' }] },
        ] },
      { id: 4,
        title: 'Microservices Patterns',
        lectures: 4,
        duration: '4 hr',
        topics: [
          { id: 1, title: 'Decomposition', videoUrl: 'https://www.youtube.com/embed/CdBtNQZH8a4', resources: [{ title: 'Decomposition guide', size: '150 KB', file: '/Asset/resources/node/decomposition.pdf' }] },
          { id: 2, title: 'Communication', videoUrl: 'https://www.youtube.com/embed/rv4LlmLmVWk', resources: [{ title: 'Comm patterns', size: '200 KB', file: '/Asset/resources/node/communication.pdf' }] },
          { id: 3, title: 'Sagas', videoUrl: 'https://www.youtube.com/embed/YPbGW3Fnmbc', resources: [{ title: 'Sagas overview', size: '100 KB', file: '/Asset/resources/node/sagas.pdf' }] },
          { id: 4, title: 'Observability', videoUrl: 'https://www.youtube.com/embed/W2wVgj-6yoY', resources: [{ title: 'Observability notes', size: '130 KB', file: '/Asset/resources/node/observability.pdf' }] },
        ] },
    ],
    whatYouWillLearn: [
      'Create RESTful APIs with Express',
      'Design microservices and communicate between services',
      'Persist data using popular databases',
    ],
    resources: [
      { title: 'API Reference', size: '1.2 MB', file: '/Asset/resources/node-api.pdf' },
    ],
  },
  {
    id: 10,
    title: 'Design Thinking for Product Teams',
  shortDescription: 'User-centric design and rapid prototyping for teams. Learn validation, usability testing, and prototype delivery.',
    description: 'Learn user-centric design and rapid prototyping for product teams. This course covers user research, ideation, and prototyping techniques with practical templates and guided workshops. You will learn to validate ideas, run usability tests, and produce prototype artifacts for stakeholders.',
    image: '/Asset/design think.png',
    rating: 4.1,
    reviews: 390,
    durationHours: 6,
    price: 0,
    totalVideos: 12,
    instructorName: 'Karim Kabir',
  instructorImage: '/Asset/karim.jpg',
    level: 'Intermediate',
    category: 'Design',
    modules: [
  { id: 1,
    title: 'Empathy & Research',
    lectures: 4,
    duration: '1.5 hr',
    topics: [
          { id: 1, title: 'User interviews', videoUrl: 'https://www.youtube.com/embed/qAws7eXItMk', resources: [{ title: 'Interview template', size: '80 KB', file: '/Asset/resources/design/interviews.pdf' }] },
          { id: 2, title: 'Surveys', videoUrl: 'https://www.youtube.com/embed/mdVWbuffdNY', resources: [{ title: 'Survey tips', size: '60 KB', file: '/Asset/resources/design/surveys.pdf' }] },
          { id: 3, title: 'Affinity mapping', videoUrl: 'https://www.youtube.com/embed/R_vLIaUYHSo', resources: [{ title: 'Affinity examples', size: '90 KB', file: '/Asset/resources/design/affinity.pdf' }] },
          { id: 4, title: 'Personas', videoUrl: 'https://www.youtube.com/embed/u44pBnAn7cM', resources: [{ title: 'Persona template', size: '70 KB', file: '/Asset/resources/design/persona.pdf' }] },
        ] },
  { id: 2,
    title: 'Ideation',
    lectures: 4,
    duration: '1 hr',
    topics: [
          { id: 1, title: 'Brainstorming', videoUrl: 'https://www.youtube.com/embed/4yKH0LZj9CU', resources: [{ title: 'Brainstorm canvas', size: '120 KB', file: '/Asset/resources/design/brainstorm.pdf' }] },
          { id: 2, title: 'Sketching', videoUrl: 'https://www.youtube.com/embed/MwidSAlbEB8', resources: [{ title: 'Sketch tips', size: '80 KB', file: '/Asset/resources/design/sketch.pdf' }] },
          { id: 3, title: 'Prioritization', videoUrl: 'https://www.youtube.com/embed/ZrGFEz2G0eE', resources: [{ title: 'Prioritization matrix', size: '60 KB', file: '/Asset/resources/design/prioritize.pdf' }] },
          { id: 4, title: 'Idea validation', videoUrl: 'https://www.youtube.com/embed/0HZGvtKWxcs', resources: [{ title: 'Validation guide', size: '100 KB', file: '/Asset/resources/design/validate.pdf' }] },
        ] },
      { id: 3,
        title: 'Prototyping',
        lectures: 4,
        duration: '2 hr',
        topics: [
          { id: 1, title: 'Low-fidelity prototyping', videoUrl: 'https://www.youtube.com/embed/cw1ZEu1xU0k', resources: [{ title: 'Lo-fi templates', size: '350 KB', file: '/Asset/resources/design/lofi.zip' }] },
          { id: 2, title: 'High-fidelity prototyping', videoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8', resources: [{ title: 'Hi-fi samples', size: '1.2 MB', file: '/Asset/resources/design/hifi.zip' }] },
          { id: 3, title: 'User testing', videoUrl: 'https://www.youtube.com/embed/0YL0xoSmyZI', resources: [{ title: 'Test script', size: '80 KB', file: '/Asset/resources/design/test-script.pdf' }] },
          { id: 4, title: 'Iterating', videoUrl: 'https://www.youtube.com/embed/h2dotaHMWCg', resources: [{ title: 'Iteration checklist', size: '50 KB', file: '/Asset/resources/design/iterate.pdf' }] },
        ] },
    ],
    whatYouWillLearn: [
      'Conduct user research',
      'Generate and validate product ideas',
      'Build low-fidelity prototypes and test them',
    ],
    resources: [
      { title: 'Design Templates', size: '3.1 MB', file: '/Asset/resources/design-templates.zip' },
    ],
  },
  {
  id: 9,
  title: 'Intro to Database',
  shortDescription: 'Practical intro to relational and NoSQL databases. Hands-on labs cover schema design and query patterns.',
  description: 'Understand relational and NoSQL databases and how to model data. Topics include ER modeling, SQL queries, indexing, transactions, and NoSQL patterns with practical examples and exercises. The course includes dataset-driven labs and schema design guidance for real applications.',
  image: '/Asset/database.jpg',
  rating: 4.0,
  reviews: 210,
  durationHours: 7,
  price: 9,
  totalVideos: 15,
  instructorName: 'Daniel Park',
  instructorImage: '/Asset/daniel.jpg',
  level: 'Beginner',
  category: 'Database',
  modules: [
    { 
      id: 1,
      title: 'Data Modeling',
      lectures: 5,
      duration: '2 hr',
      topics: [
        { id: 1, title: 'ER modeling', videoUrl: 'https://www.youtube.com/embed/QpdhBUYk7Kk', resources: [{ title: 'ER guide', size: '200 KB', file: '/Asset/resources/db/er-guide.pdf' }] },
        { id: 2, title: 'Normalization', videoUrl: 'https://www.youtube.com/embed/ABwD8IYByfk', resources: [{ title: 'Normalization notes', size: '120 KB', file: '/Asset/resources/db/normalization.pdf' }] },
        { id: 3, title: 'Relationships', videoUrl: 'https://www.youtube.com/embed/N0cXy_LD0TY', resources: [{ title: 'Relationship types', size: '90 KB', file: '/Asset/resources/db/relationships.pdf' }] },
        { id: 4, title: 'Design tradeoffs', videoUrl: 'https://www.youtube.com/embed/W2Z7fbCLSTw', resources: [{ title: 'Design tradeoffs', size: '80 KB', file: '/Asset/resources/db/tradeoffs.pdf' }] },
        { id: 5, title: 'Schema Design', videoUrl: 'https://www.youtube.com/embed/3BZz8R7mqu0', resources: [{ title: 'Schema design principles', size: '150 KB', file: '/Asset/resources/db/schema-design.pdf' }] }  // Added topic
      ]
    },
    { 
      id: 2,
      title: 'SQL Basics',
      lectures: 5,
      duration: '3 hr',
      topics: [
        { id: 1, title: 'SELECT & JOINs', videoUrl: 'https://www.youtube.com/embed/9yeOJ0ZMUYw', resources: [{ title: 'Query cheatsheet', size: '150 KB', file: '/Asset/resources/db/queries.pdf' }] },
        { id: 2, title: 'Aggregation', videoUrl: 'https://www.youtube.com/embed/3-jwsaGvD8k', resources: [{ title: 'Aggregation examples', size: '120 KB', file: '/Asset/resources/db/aggregation.pdf' }] },
        { id: 3, title: 'Indexes', videoUrl: 'https://www.youtube.com/embed/-qNSXK7s7_w', resources: [{ title: 'Index guide', size: '110 KB', file: '/Asset/resources/db/indexes.pdf' }] },
        { id: 4, title: 'Transactions', videoUrl: 'https://www.youtube.com/embed/P80Js_qClUE', resources: [{ title: 'Transactions notes', size: '90 KB', file: '/Asset/resources/db/transactions.pdf' }] },
        { id: 5, title: 'Subqueries', videoUrl: 'https://www.youtube.com/embed/m1KcNV-Zhzs', resources: [{ title: 'Subqueries tutorial', size: '130 KB', file: '/Asset/resources/db/subqueries.pdf' }] }  // Added topic
      ]
    },
    { 
      id: 3,
      title: 'NoSQL Patterns',
      lectures: 5, 
      duration: '1.5 hr',
      topics: [
        { id: 1, title: 'Document stores', videoUrl: 'https://www.youtube.com/embed/0buKQHokLK8', resources: [{ title: 'Docs primer', size: '140 KB', file: '/Asset/resources/db/document-stores.pdf' }] },
        { id: 2, title: 'Key-value', videoUrl: 'https://www.youtube.com/embed/ruz-vK8IesE', resources: [{ title: 'KV patterns', size: '100 KB', file: '/Asset/resources/db/kv.pdf' }] },
        { id: 3, title: 'When to choose NoSQL', videoUrl: 'https://www.youtube.com/embed/qI_g07C_Q5I', resources: [{ title: 'Decision guide', size: '120 KB', file: '/Asset/resources/db/when-nosql.pdf' }] },
        { id: 4, title: 'CAP theorem', videoUrl: 'https://www.youtube.com/embed/k-Yaq8AHlFA', resources: [{ title: 'CAP summary', size: '80 KB', file: '/Asset/resources/db/cap.pdf' }] },
        { id: 5, title: 'Column-family stores', videoUrl: 'https://www.youtube.com/embed/RqvBfK33RqM', resources: [{ title: 'Column-family stores overview', size: '110 KB', file: '/Asset/resources/db/column-family.pdf' }] }  // Added topic
      ]
    }
  ],
  whatYouWillLearn: [
    'Model relational data',
    'Write SQL queries',
    'Choose when to use NoSQL',
  ],
  resources: [
    { title: 'Sample ER Diagrams', size: '900 KB', file: '/Asset/resources/er-diagrams.pdf' },
  ],
},
  {
  id: 8,
  title: 'Python Crash Course',
  shortDescription: 'Fast-paced Python for prototyping and scripting. Covers practical scripts, data handling, and real examples.',
  description: 'A fast-paced introduction to Python for beginners and engineers who want to prototype quickly. You will learn core syntax, data structures, scripting tools, and advanced topics like decorators and generators. Each module includes code examples, exercises, and downloadable scripts to practice.',
  image: '/Asset/python.webp',
  rating: 4.6,
  reviews: 890,
  durationHours: 8,
  price: 10,
  totalVideos: 20,
  instructorName: 'Karan Sharma',
  instructorImage: '/Asset/karan.jpg',
  level: 'Beginner',
  category: 'Programming',
  modules: [
    { 
      id: 1, 
      title: 'Python Basics', 
      lectures: 5, 
      duration: '2.5 hr', 
      topics: [
        { id: 1, title: 'Syntax & variables', videoUrl: 'https://www.youtube.com/embed/kqtD5dpn9C8', resources: [{ title: 'Syntax cheatsheet', size: '80 KB', file: '/Asset/resources/python/syntax.pdf' }] },
        { id: 2, title: 'Control flow', videoUrl: 'https://www.youtube.com/embed/PqFKRqpHrjw', resources: [{ title: 'Flow examples', size: '90 KB', file: '/Asset/resources/python/flow.pdf' }] },
        { id: 3, title: 'Functions', videoUrl: 'https://www.youtube.com/embed/9Os0o3wzS_I', resources: [{ title: 'Functions guide', size: '110 KB', file: '/Asset/resources/python/functions.pdf' }] },
        { id: 4, title: 'Modules & packages', videoUrl: 'https://www.youtube.com/embed/CqvZ3vGoGs0', resources: [{ title: 'Packaging', size: '120 KB', file: '/Asset/resources/python/packages.pdf' }] },
        { id: 5, title: 'Error handling', videoUrl: 'https://www.youtube.com/embed/NIWwJbo-9_8', resources: [{ title: 'Error handling tutorial', size: '90 KB', file: '/Asset/resources/python/errors.pdf' }] } // Added 5th topic
      ]
    },
    { 
      id: 2, 
      title: 'Data Structures', 
      lectures: 5, 
      duration: '2 hr', 
      topics: [
        { id: 1, title: 'Lists & tuples', videoUrl: 'https://www.youtube.com/embed/tw7ror9x32s', resources: [{ title: 'Lists examples', size: '100 KB', file: '/Asset/resources/python/lists.pdf' }] },
        { id: 2, title: 'Dictionaries', videoUrl: 'https://www.youtube.com/embed/XCcpzWs-CI4', resources: [{ title: 'Dicts guide', size: '90 KB', file: '/Asset/resources/python/dicts.pdf' }] },
        { id: 3, title: 'Sets', videoUrl: 'https://www.youtube.com/embed/sBvaPopWOmQ', resources: [{ title: 'Sets notes', size: '60 KB', file: '/Asset/resources/python/sets.pdf' }] },
        { id: 4, title: 'Comprehensions', videoUrl: 'https://www.youtube.com/embed/AhSvKGTh28Q', resources: [{ title: 'Comprehensions', size: '80 KB', file: '/Asset/resources/python/comprehensions.pdf' }] },
        { id: 5, title: 'Queues & Stacks', videoUrl: 'https://www.youtube.com/embed/L3ud3rXpIxA', resources: [{ title: 'Queues & Stacks notes', size: '110 KB', file: '/Asset/resources/python/queues-stacks.pdf' }] } // Added 5th topic
      ]
    },
    { 
      id: 3, 
      title: 'Scripting & Tools', 
      lectures: 5, 
      duration: '2 hr', 
      topics: [
        { id: 1, title: 'File I/O', videoUrl: 'https://www.youtube.com/embed/Uh2ebFW8OYM', resources: [{ title: 'File examples', size: '70 KB', file: '/Asset/resources/python/file-io.pdf' }] },
        { id: 2, title: 'Virtualenv & pip', videoUrl: 'https://www.youtube.com/embed/APOPm01BVrk', resources: [{ title: 'Env guide', size: '60 KB', file: '/Asset/resources/python/env.pdf' }] },
        { id: 3, title: 'argparse', videoUrl: 'https://www.youtube.com/embed/88pl8TuuKz0', resources: [{ title: 'Argparse cheat', size: '50 KB', file: '/Asset/resources/python/argparse.pdf' }] },
        { id: 4, title: 'Working with libs', videoUrl: 'https://www.youtube.com/embed/KSiRzuSx120', resources: [{ title: 'Libraries list', size: '120 KB', file: '/Asset/resources/python/libs.pdf' }] },
        { id: 5, title: 'Debugging Tools', videoUrl: 'https://www.youtube.com/embed/5AYIe-3cD-s', resources: [{ title: 'Debugger guide', size: '80 KB', file: '/Asset/resources/python/debugger.pdf' }] } // Added 5th topic
      ]
    },
    { 
      id: 4, 
      title: 'Advanced Python', 
      lectures: 5, 
      duration: '2 hr', 
      topics: [
        { id: 1, title: 'Decorators', videoUrl: 'https://www.youtube.com/embed/r7Dtus7N4pI', resources: [{ title: 'Decorators tutorial', size: '130 KB', file: '/Asset/resources/python/decorators.pdf' }] },
        { id: 2, title: 'Generators', videoUrl: 'https://www.youtube.com/embed/bD05uGo_sVI', resources: [{ title: 'Generators guide', size: '120 KB', file: '/Asset/resources/python/generators.pdf' }] },
        { id: 3, title: 'Context Managers', videoUrl: 'https://www.youtube.com/embed/iba-I4CrmyA', resources: [{ title: 'Context manager notes', size: '110 KB', file: '/Asset/resources/python/context-managers.pdf' }] },
        { id: 4, title: 'Metaprogramming', videoUrl: 'https://www.youtube.com/embed/htEECzKJBXk', resources: [{ title: 'Metaprogramming intro', size: '140 KB', file: '/Asset/resources/python/metaprogramming.pdf' }] },
        { id: 5, title: 'Concurrency', videoUrl: 'https://www.youtube.com/embed/9zinZmE3Ogk', resources: [{ title: 'Concurrency in Python', size: '150 KB', file: '/Asset/resources/python/concurrency.pdf' }] } // Added 5th topic
      ]
    },
  ],
  whatYouWillLearn: [
    'Write Python programs',
    'Work with lists, dicts and files',
    'Use standard libraries to automate tasks',
    'Understand advanced Python concepts like decorators, generators, and metaprogramming',
  ],
  resources: [
    { title: 'Code Examples', size: '1.2 MB', file: '/Asset/resources/python-examples.zip' },
  ],
},
  {
    id: 7,
    title: 'Advanced React Patterns',
  shortDescription: 'Advanced React patterns for scaling apps. Learn advanced hooks, state architecture, and profiling techniques.',
  description: 'Take your React skills to the next level with hooks, context, and performance patterns. Focused lessons cover advanced hooks, state architecture, and profiling strategies to scale React applications. Includes pattern libraries, practical refactors, and exercises to optimize real-world apps.',
    image: '/Asset/advance react.jpg',
    rating: 4.4,
    reviews: 640,
    durationHours: 10,
    price: 30,
    totalVideos: 12,
    instructorName: 'Morgan Lee',
    instructorImage: '/Asset/morgan lee.jpg',
    level: 'Advanced',
    category: 'Web Development',
    modules: [
      { id: 1,
        title: 'Hooks Deep-dive',
        lectures: 4,
        duration: '2.5 hr',
        topics: [
          { id: 1, title: 'useEffect & timing', videoUrl: 'https://www.youtube.com/embed/0ZJgIjIuY7U', resources: [{ title: 'useEffect notes', size: '80 KB', file: '/Asset/resources/react/useeffect.pdf' }] },
          { id: 2, title: 'useMemo & useCallback', videoUrl: 'https://www.youtube.com/embed/THL1OPn72vo', resources: [{ title: 'Memo patterns', size: '90 KB', file: '/Asset/resources/react/memo.pdf' }] },
          { id: 3, title: 'Custom hooks', videoUrl: 'https://www.youtube.com/embed/J-g9ZJha8FE', resources: [{ title: 'Custom hooks guide', size: '110 KB', file: '/Asset/resources/react/custom-hooks.pdf' }] },
          { id: 4, title: 'Testing hooks', videoUrl: 'https://www.youtube.com/embed/TBZy-Rc-xX0', resources: [{ title: 'Testing hooks', size: '100 KB', file: '/Asset/resources/react/test-hooks.pdf' }] },
        ] },
      { id: 2,
        title: 'Context & Patterns',
        lectures: 4,
        duration: '2 hr',
        topics: [
          { id: 1, title: 'Context usage', videoUrl: 'https://www.youtube.com/embed/5LrDIWkK_Bc', resources: [{ title: 'Context examples', size: '90 KB', file: '/Asset/resources/react/context.pdf' }] },
          { id: 2, title: 'State colocation', videoUrl: 'https://www.youtube.com/embed/wmQ8jAYUVSQ', resources: [{ title: 'State strategies', size: '80 KB', file: '/Asset/resources/react/state.pdf' }] },
          { id: 3, title: 'Composition patterns', videoUrl: 'https://www.youtube.com/embed/w6fodPZknPw', resources: [{ title: 'Composition', size: '70 KB', file: '/Asset/resources/react/composition.pdf' }] },
          { id: 4, title: 'Render props vs hooks', videoUrl: 'https://www.youtube.com/embed/PrXh5rmJIQQ', resources: [{ title: 'Patterns compare', size: '60 KB', file: '/Asset/resources/react/pattern-compare.pdf' }] },
        ] },
      { id: 3,
        title: 'Performance',
        lectures: 4,
        duration: '2 hr',
        topics: [
          { id: 1, title: 'Profiling', videoUrl: 'https://www.youtube.com/embed/00RoZflFE34', resources: [{ title: 'Profiler guide', size: '120 KB', file: '/Asset/resources/react/profiler.pdf' }] },
          { id: 2, title: 'Code-splitting', videoUrl: 'https://www.youtube.com/embed/JU6sl_yyZqs', resources: [{ title: 'Code-splitting', size: '90 KB', file: '/Asset/resources/react/code-split.pdf' }] },
          { id: 3, title: 'Optimizing renders', videoUrl: 'https://www.youtube.com/embed/qOQClO3g8-Y', resources: [{ title: 'Render tips', size: '80 KB', file: '/Asset/resources/react/optimize.pdf' }] },
          { id: 4, title: 'Memoization', videoUrl: 'https://www.youtube.com/embed/DEPwA3mv_R8', resources: [{ title: 'Memo guide', size: '70 KB', file: '/Asset/resources/react/memoization.pdf' }] },
        ] },
    ],
    whatYouWillLearn: [
      'Use advanced hooks patterns',
      'Structure large React apps',
      'Improve runtime performance',
    ],
    resources: [
      { title: 'Pattern Library', size: '2.0 MB', file: '/Asset/resources/react-patterns.pdf' },
    ],
  },
  {
  id: 6,
  title: 'Web Development Bootcamp',
  shortDescription: 'Fullstack web dev — HTML, CSS, JS to deployment. Build and deploy a starter app with guided templates.',
  description: 'Become a fullstack web developer by taking this ONE course, even if you have never coded before. Learn HTML, CSS, JavaScript, Node.js, and deployment through guided projects and starter templates. By the end you will deploy a fullstack app and understand the core workflows used in modern development.',
  image: '/Asset/webdev.jpg',
  rating: 4.9,
  reviews: 3530,
  durationHours: 12,
  price: 0,
  totalVideos: 16,
  instructorName: 'Karim Kabir',
  instructorImage: '/Asset/karim.jpg',
  level: 'Beginner',
  category: 'Web Development',
  modules: [
    { 
      id: 1, 
      title: 'HTML & CSS', 
      lectures: 4, 
      duration: '3 hr', 
      topics: [
        { id: 1, title: 'HTML semantics', videoUrl: 'https://www.youtube.com/embed/UB1O30fR-EE', resources: [{ title: 'HTML checklist', size: '80 KB', file: '/Asset/resources/web/html.pdf' }] },
        { id: 2, title: 'CSS basics', videoUrl: 'https://www.youtube.com/embed/1PnVor36_40', resources: [{ title: 'CSS guide', size: '120 KB', file: '/Asset/resources/web/css.pdf' }] },
        { id: 3, title: 'Flexbox & Grid', videoUrl: 'https://www.youtube.com/embed/3YW65K6LcIA', resources: [{ title: 'Layout cheatsheet', size: '140 KB', file: '/Asset/resources/web/layout.pdf' }] },
        { id: 4, title: 'Responsive design', videoUrl: 'https://www.youtube.com/embed/srvUrASNj0s', resources: [{ title: 'Responsive tips', size: '90 KB', file: '/Asset/resources/web/responsive.pdf' }] },
      ] 
    },
    { 
      id: 2, 
      title: 'JavaScript Fundamentals', 
      lectures: 4, 
      duration: '4 hr', 
      topics: [
        { id: 1, title: 'DOM manipulation', videoUrl: 'https://www.youtube.com/embed/y17RuWkWdn8', resources: [{ title: 'DOM guide', size: '110 KB', file: '/Asset/resources/web/dom.pdf' }] },
        { id: 2, title: 'ES6+', videoUrl: 'https://www.youtube.com/embed/nZ1DMMsyVyI', resources: [{ title: 'ES6 features', size: '130 KB', file: '/Asset/resources/web/es6.pdf' }] },
        { id: 3, title: 'Async patterns', videoUrl: 'https://www.youtube.com/embed/PoRJizFvM7s', resources: [{ title: 'Async patterns', size: '120 KB', file: '/Asset/resources/web/async.pdf' }] },
        { id: 4, title: 'Fetch & AJAX', videoUrl: 'https://www.youtube.com/embed/cuEtnrL9-H0', resources: [{ title: 'Network guide', size: '90 KB', file: '/Asset/resources/web/fetch.pdf' }] },
      ] 
    },
    { 
      id: 3, 
      title: 'Backend with Node', 
      lectures: 4, 
      duration: '4 hr', 
      topics: [
        { id: 1, title: 'Intro to Node', videoUrl: 'https://www.youtube.com/embed/TlB_eWDSMt4', resources: [{ title: 'Node primer', size: '100 KB', file: '/Asset/resources/web/node-primer.pdf' }] },
        { id: 2, title: 'Express basics', videoUrl: 'https://www.youtube.com/embed/L72fhGm1tfE', resources: [{ title: 'Express cheatsheet', size: '110 KB', file: '/Asset/resources/web/express.pdf' }] },
        { id: 3, title: 'Routing & APIs', videoUrl: 'https://www.youtube.com/embed/pKd0Rpw7O48', resources: [{ title: 'APIs guide', size: '120 KB', file: '/Asset/resources/web/apis.pdf' }] },
        { id: 4, title: 'Deployment', videoUrl: 'https://www.youtube.com/embed/l134cBAJCuc', resources: [{ title: 'Deploy notes', size: '150 KB', file: '/Asset/resources/web/deploy.pdf' }] },
      ] 
    },
    { 
      id: 4, 
      title: 'Advanced JavaScript', 
      lectures: 4, 
      duration: '3 hr', 
      topics: [
        { id: 1, title: 'Event Handling', videoUrl: 'https://www.youtube.com/embed/XF1_MlZ5l6M', resources: [{ title: 'Event Handling Guide', size: '110 KB', file: '/Asset/resources/web/events.pdf' }] },
        { id: 2, title: 'Asynchronous JS', videoUrl: 'https://www.youtube.com/embed/ZYb_ZU8LNxs', resources: [{ title: 'Async JS Concepts', size: '120 KB', file: '/Asset/resources/web/asyncjs.pdf' }] },
        { id: 3, title: 'Promises & Callbacks', videoUrl: 'https://www.youtube.com/embed/DHvZLI7Db8E', resources: [{ title: 'Promises and Callbacks', size: '140 KB', file: '/Asset/resources/web/promises.pdf' }] },
        { id: 4, title: 'JavaScript ES6+', videoUrl: 'https://www.youtube.com/embed/NCwa_xi0Uuc', resources: [{ title: 'ES6+ Features', size: '130 KB', file: '/Asset/resources/web/es6plus.pdf' }] },
      ] 
    },
  ],
  whatYouWillLearn: [
    'Build responsive websites',
    'Write JavaScript for the browser and server',
    'Deploy fullstack applications',
    'Work with advanced JavaScript concepts',
  ],
  resources: [
    { title: 'Starter Templates', size: '3.5 MB', file: '/Asset/resources/web-templates.zip' },
  ],
},
  {
  id: 5,
  title: 'UI/UX Fundamentals',
  shortDescription: 'Foundations of UI/UX: design, wireframing, prototypes. Hands-on exercises and a ready-to-use UI kit included.',
  description: 'Do you love designing? If so, this course is the perfect one for you. Learn UI/UX foundations, wireframing, and prototyping tools with practical exercises and a complete UI kit. The course emphasizes real design workflows, handoff best practices, and portfolio-ready projects.',
  image: '/Asset/uiux.webp',
  rating: 2.9,
  reviews: 2570,
  durationHours: 5,
  price: 14,
  totalVideos: 14,
  instructorName: 'Karim Kabir',
  instructorImage: '/Asset/karim.jpg',
  level: 'Beginner',
  category: 'Design',
  modules: [
    { 
      id: 1, 
      title: 'Design Basics', 
      lectures: 5, 
      duration: '2 hr', 
      topics: [
        { id: 1, title: 'Principles', videoUrl: 'https://www.youtube.com/embed/YqQx75OPRa0', resources: [{ title: 'Design principles', size: '90 KB', file: '/Asset/resources/ui/principles.pdf' }] },
        { id: 2, title: 'Color theory', videoUrl: 'https://www.youtube.com/embed/_2LLXnUdUIc', resources: [{ title: 'Color guide', size: '80 KB', file: '/Asset/resources/ui/color.pdf' }] },
        { id: 3, title: 'Typography', videoUrl: 'https://www.youtube.com/embed/sByzHoiYFX0', resources: [{ title: 'Typography notes', size: '60 KB', file: '/Asset/resources/ui/typography.pdf' }] },
        { id: 4, title: 'Layout', videoUrl: 'https://www.youtube.com/embed/3C_22eBWpjg', resources: [{ title: 'Layout tips', size: '70 KB', file: '/Asset/resources/ui/layout.pdf' }] },
        { id: 5, title: 'Design tools overview', videoUrl: 'https://www.youtube.com/embed/c9Wg6Cb_YlU', resources: [{ title: 'Tools guide', size: '100 KB', file: '/Asset/resources/ui/tools.pdf' }] },
      ] 
    },
    { 
      id: 2, 
      title: 'Wireframing', 
      lectures: 5, 
      duration: '1.5 hr', 
      topics: [
        { id: 1, title: 'Low-fi patterns', videoUrl: 'https://www.youtube.com/embed/qpH7-KFWZRI', resources: [{ title: 'Lo-fi templates', size: '250 KB', file: '/Asset/resources/ui/lofi.zip' }] },
        { id: 2, title: 'Flow mapping', videoUrl: 'https://www.youtube.com/embed/Tvu3SXFdzqU', resources: [{ title: 'Flow samples', size: '120 KB', file: '/Asset/resources/ui/flow.pdf' }] },
        { id: 3, title: 'Annotations', videoUrl: 'https://www.youtube.com/embed/LMFJjKhICFw', resources: [{ title: 'Annotation guide', size: '60 KB', file: '/Asset/resources/ui/annotations.pdf' }] },
        { id: 4, title: 'Wireframe checklist', videoUrl: 'https://www.youtube.com/embed/KnZrypOaVCg', resources: [{ title: 'Checklist', size: '40 KB', file: '/Asset/resources/ui/checklist.pdf' }] },
        { id: 5, title: 'Interactive wireframes', videoUrl: 'https://www.youtube.com/embed/eN4iCAAf-gY', resources: [{ title: 'Interactive wireframes guide', size: '150 KB', file: '/Asset/resources/ui/interactives.pdf' }] },
      ] 
    },
    { 
      id: 3, 
      title: 'Prototyping Tools', 
      lectures: 4, 
      duration: '1 hr', 
      topics: [
        { id: 1, title: 'Figma basics', videoUrl: 'https://www.youtube.com/embed/FTFaQWZBqQ8', resources: [{ title: 'Figma cheats', size: '200 KB', file: '/Asset/resources/ui/figma.pdf' }] },
        { id: 2, title: 'Prototype interactions', videoUrl: 'https://www.youtube.com/embed/X5qiBwqptek', resources: [{ title: 'Interactions guide', size: '120 KB', file: '/Asset/resources/ui/interactions.pdf' }] },
        { id: 3, title: 'Exporting assets', videoUrl: 'https://www.youtube.com/embed/vCvtgr0zF-o', resources: [{ title: 'Export guide', size: '80 KB', file: '/Asset/resources/ui/export.pdf' }] },
        { id: 4, title: 'Design tokens', videoUrl: 'https://www.youtube.com/embed/wtTstdiBuUk', resources: [{ title: 'Tokens primer', size: '60 KB', file: '/Asset/resources/ui/tokens.pdf' }] },
      ] 
    },
  ],
  whatYouWillLearn: [
    'Design usable interfaces',
    'Create wireframes and prototypes',
    'Design handoff best practices',
    'Use advanced design tools',
  ],
  resources: [
    { title: 'UI Kit', size: '4.2 MB', file: '/Asset/resources/ui-kit.zip' },
  ],
},
  {
  id: 4,
  title: 'Data Science with Python',
  shortDescription: 'Data science with Python: cleaning, modeling, deployment. Learn with notebooks and practical datasets.',
  description: 'Learn data science with python by taking this course, and build your desired career. Covers data cleaning, exploration, modeling basics, and evaluation with hands-on notebooks and practical datasets. You will also get guidance on deploying models and assembling a data-science portfolio.',
  image: '/Asset/data science.jpeg',
  rating: 3.9,
  reviews: 1340,
  durationHours: 18,
  price: 25,
  totalVideos: 15,
  instructorName: 'Jashim Uddin',
  instructorImage: '/Asset/jashim uddin.jpg',
  level: 'Intermediate',
  category: 'Data Science',
  modules: [
    { 
      id: 1, 
      title: 'Python for Data', 
      lectures: 5, 
      duration: '5 hr', 
      topics: [
        { id: 1, title: 'Jupyter & tooling', resources: [{ title: 'Jupyter tips', size: '120 KB', file: '/Asset/resources/ds/jupyter.pdf' }] },
        { id: 2, title: 'Data cleaning', resources: [{ title: 'Cleaning checklist', size: '140 KB', file: '/Asset/resources/ds/cleaning.pdf' }] },
        { id: 3, title: 'Exploration', resources: [{ title: 'EDA notes', size: '160 KB', file: '/Asset/resources/ds/eda.pdf' }] },
        { id: 4, title: 'Visualization', resources: [{ title: 'Viz examples', size: '200 KB', file: '/Asset/resources/ds/viz.pdf' }] },
        { id: 5, title: 'Advanced Jupyter features', resources: [{ title: 'Advanced Jupyter', size: '180 KB', file: '/Asset/resources/ds/advanced-jupyter.pdf' }] },
      ] 
    },
    { 
      id: 2, 
      title: 'Pandas & NumPy', 
      lectures: 5, 
      duration: '5 hr', 
      topics: [
        { id: 1, title: 'NumPy basics', resources: [{ title: 'NumPy primer', size: '200 KB', file: '/Asset/resources/ds/numpy.pdf' }] },
        { id: 2, title: 'Pandas Series/DataFrame', resources: [{ title: 'Pandas guide', size: '300 KB', file: '/Asset/resources/ds/pandas.pdf' }] },
        { id: 3, title: 'Grouping & joins', resources: [{ title: 'Grouping notes', size: '120 KB', file: '/Asset/resources/ds/grouping.pdf' }] },
        { id: 4, title: 'Performance tips', resources: [{ title: 'Performance', size: '100 KB', file: '/Asset/resources/ds/performance.pdf' }] },
        { id: 5, title: 'Pandas advanced functions', resources: [{ title: 'Advanced pandas', size: '180 KB', file: '/Asset/resources/ds/advanced-pandas.pdf' }] },
      ] 
    },
    { 
      id: 3, 
      title: 'Modeling Basics', 
      lectures: 5, 
      duration: '5 hr', 
      topics: [
        { id: 1, title: 'Supervised learning', resources: [{ title: 'Supervised primer', size: '220 KB', file: '/Asset/resources/ds/supervised.pdf' }] },
        { id: 2, title: 'Model evaluation', resources: [{ title: 'Evaluation guide', size: '150 KB', file: '/Asset/resources/ds/evaluation.pdf' }] },
        { id: 3, title: 'Feature engineering', resources: [{ title: 'Feature tips', size: '130 KB', file: '/Asset/resources/ds/feature.pdf' }] },
        { id: 4, title: 'Model deployment', resources: [{ title: 'Deploy notes', size: '200 KB', file: '/Asset/resources/ds/deploy.pdf' }] },
        { id: 5, title: 'Unsupervised learning basics', resources: [{ title: 'Unsupervised primer', size: '180 KB', file: '/Asset/resources/ds/unsupervised.pdf' }] },
      ] 
    },
  ],
  whatYouWillLearn: [
    'Process data with Pandas',
    'Build basic machine learning models',
    'Evaluate model performance',
    'Apply advanced machine learning concepts',
  ],
  resources: [
    { title: 'Datasets', size: '8.1 MB', file: '/Asset/resources/datasets.zip' },
  ],
},
  {
  id: 3,
  title: 'HTML, CSS, JS Basics',
  shortDescription: 'Frontend basics: HTML, CSS, and vanilla JavaScript. Build small projects and deploy simple applications.',
  description: 'Learn frontend development from the ground up. This course covers semantic HTML, responsive CSS, and vanilla JavaScript with practical projects and deployable examples. You will build small applications to reinforce concepts and prepare for more advanced frontend work.',
  image: '/Asset/html-css-javascript.jpg',
  rating: 3.8,
  reviews: 2200,
  durationHours: 12,
  price: 0,
  totalVideos: 20,
  instructorName: 'Emily Rose',
  instructorImage: '/Asset/emily rose.jpg',
  level: 'Beginner',
  category: 'Web Development',
  modules: [
    { 
      id: 1, 
      title: 'HTML Essentials', 
      lectures: 5, 
      duration: '4 hr', 
      topics: [
        { id: 1, title: 'Tags & semantics', resources: [{ title: 'Tags reference', size: '110 KB', file: '/Asset/resources/frontend/tags.pdf' }] },
        { id: 2, title: 'Forms', resources: [{ title: 'Forms guide', size: '90 KB', file: '/Asset/resources/frontend/forms.pdf' }] },
        { id: 3, title: 'Accessibility basics', resources: [{ title: 'A11y checklist', size: '80 KB', file: '/Asset/resources/frontend/a11y.pdf' }] },
        { id: 4, title: 'SEO basics', resources: [{ title: 'SEO notes', size: '70 KB', file: '/Asset/resources/frontend/seo.pdf' }] },
        { id: 5, title: 'HTML5 APIs', resources: [{ title: 'HTML5 API overview', size: '100 KB', file: '/Asset/resources/frontend/html5-api.pdf' }] }
      ] 
    },
    { 
      id: 2, 
      title: 'CSS Layouts', 
      lectures: 5, 
      duration: '4.5 hr', 
      topics: [
        { id: 1, title: 'Flexbox', resources: [{ title: 'Flexbox cheatsheet', size: '100 KB', file: '/Asset/resources/frontend/flexbox.pdf' }] },
        { id: 2, title: 'Grid', resources: [{ title: 'Grid examples', size: '120 KB', file: '/Asset/resources/frontend/grid.pdf' }] },
        { id: 3, title: 'Responsive patterns', resources: [{ title: 'Responsive examples', size: '140 KB', file: '/Asset/resources/frontend/responsive.pdf' }] },
        { id: 4, title: 'Utilities', resources: [{ title: 'Utility classes', size: '80 KB', file: '/Asset/resources/frontend/utilities.pdf' }] },
        { id: 5, title: 'Flexbox vs Grid', resources: [{ title: 'Flex vs Grid guide', size: '130 KB', file: '/Asset/resources/frontend/flex-vs-grid.pdf' }] }
      ] 
    },
    { 
      id: 3, 
      title: 'JavaScript Basics', 
      lectures: 5, 
      duration: '4.5 hr', 
      topics: [
        { id: 1, title: 'Variables & types', resources: [{ title: 'Types guide', size: '60 KB', file: '/Asset/resources/frontend/types.pdf' }] },
        { id: 2, title: 'Functions & scope', resources: [{ title: 'Scope notes', size: '70 KB', file: '/Asset/resources/frontend/scope.pdf' }] },
        { id: 3, title: 'Events', resources: [{ title: 'Events guide', size: '90 KB', file: '/Asset/resources/frontend/events.pdf' }] },
        { id: 4, title: 'DOM APIs', resources: [{ title: 'DOM API examples', size: '100 KB', file: '/Asset/resources/frontend/dom-api.pdf' }] },
        { id: 5, title: 'ES6 features', resources: [{ title: 'ES6 syntax', size: '120 KB', file: '/Asset/resources/frontend/es6.pdf' }] }
      ] 
    },
    { 
      id: 4, 
      title: 'Advanced JavaScript Concepts', 
      lectures: 5, 
      duration: '4.5 hr', 
      topics: [
        { id: 1, title: 'Closures', resources: [{ title: 'Closures guide', size: '150 KB', file: '/Asset/resources/frontend/closures.pdf' }] },
        { id: 2, title: 'Asynchronous JS', resources: [{ title: 'Async JS notes', size: '160 KB', file: '/Asset/resources/frontend/async.pdf' }] },
        { id: 3, title: 'Prototypal Inheritance', resources: [{ title: 'Inheritance notes', size: '170 KB', file: '/Asset/resources/frontend/inheritance.pdf' }] },
        { id: 4, title: 'ES6 Classes', resources: [{ title: 'ES6 class overview', size: '140 KB', file: '/Asset/resources/frontend/es6-classes.pdf' }] },
        { id: 5, title: 'JavaScript Design Patterns', resources: [{ title: 'Design patterns', size: '180 KB', file: '/Asset/resources/frontend/design-patterns.pdf' }] }
      ] 
    },
  ],
  whatYouWillLearn: [
    'Build semantic HTML pages',
    'Style responsive layouts with CSS',
    'Add interactivity using vanilla JS',
    'Master advanced JavaScript techniques',
  ],
  resources: [
    { title: 'Boilerplate', size: '1.1 MB', file: '/Asset/resources/frontend-boilerplate.zip' },
  ],
},
  {
    id: 2,
    title: 'Manual and Automated Testing',
  shortDescription: 'Hands-on manual and automated testing fundamentals. Covers tooling, scripting, and CI integration with labs.',
  description: 'Learn testing fundamentals for both manual and automated approaches. This course covers tooling setup, test case design, automation scripting, and CI integration with hands-on labs and example scripts. It is ideal for learners who want practical testing experience and reusable resources.',
    image: '/Asset/testing.jpg',
    rating: 4.7,
    reviews: 1100,
    durationHours: 11,
    price: 12,
    totalVideos: 12,
    instructorName: 'Kate Weber',
    instructorImage: '/Asset/Kate weber.png',
    level: 'Intermediate',
    category: 'Software Testing',
    modules: [
  { id: 1,
    title: 'Intro & Tools',
    lectures: 4,
    duration: '1.5 hr',
    topics: [
          { id: 1, title: 'Testing tools', resources: [{ title: 'Tools list', size: '120 KB', file: '/Asset/resources/testing/tools-list.pdf' }] },
          { id: 2, title: 'Setting up', resources: [{ title: 'Setup guide', size: '150 KB', file: '/Asset/resources/testing/setup.pdf' }] },
          { id: 3, title: 'Test environments', resources: [{ title: 'Env notes', size: '90 KB', file: '/Asset/resources/testing/env.pdf' }] },
          { id: 4, title: 'Local workflow', resources: [{ title: 'Workflow', size: '80 KB', file: '/Asset/resources/testing/workflow-local.pdf' }] },
        ] },
  { id: 2,
    title: 'Manual Testing',
    lectures: 4,
    duration: '3 hr',
    topics: [
          { id: 1, title: 'Test scenarios', resources: [{ title: 'Scenario templates', size: '110 KB', file: '/Asset/resources/testing/scenarios.pdf' }] },
          { id: 2, title: 'Test data', resources: [{ title: 'Data examples', size: '90 KB', file: '/Asset/resources/testing/test-data.pdf' }] },
          { id: 3, title: 'Reporting', resources: [{ title: 'Reporting template', size: '70 KB', file: '/Asset/resources/testing/reporting.pdf' }] },
          { id: 4, title: 'Review process', resources: [{ title: 'Review checklist', size: '60 KB', file: '/Asset/resources/testing/review.pdf' }] },
        ] },
  { id: 3,
    title: 'Test Automation',
    lectures: 4,
    duration: '4 hr',
    topics: [
          { id: 1, title: 'Automation basics', resources: [{ title: 'Automation intro', size: '130 KB', file: '/Asset/resources/testing/auto-intro.pdf' }] },
          { id: 2, title: 'Scripting', resources: [{ title: 'Scripting guide', size: '140 KB', file: '/Asset/resources/testing/scripting.pdf' }] },
          { id: 3, title: 'Frameworks', resources: [{ title: 'Framework list', size: '160 KB', file: '/Asset/resources/testing/frameworks.pdf' }] },
          { id: 4, title: 'CI pipelines', resources: [{ title: 'CI examples', size: '180 KB', file: '/Asset/resources/testing/ci-examples.pdf' }] },
        ] },
    ],
    whatYouWillLearn: [
      'Design manual tests',
      'Automate tests using modern tools',
      'Interpret test reports',
    ],
    resources: [
      { title: 'Test Scripts', size: '900 KB', file: '/Asset/resources/test-scripts.zip' },
    ],
  },
  {
    id: 1,
    title: 'Web Development with MERN',
  shortDescription: 'Project-based MERN stack: build and deploy fullstack apps. Includes auth, data modeling, and deployment exercises.',
  description: 'Master the MERN stack by building real projects and end-to-end features. The course covers React frontend patterns, Node/Express APIs, MongoDB data modeling, authentication, and deployment. Includes starter templates, step-by-step labs, and exercises to reinforce each layer of the stack.',
    image: '/Asset/mern stack.jpg',
    rating: 4.8,
    reviews: 2340,
    durationHours: 16,
    price: 22,
    totalVideos: 16,
    instructorName: 'Sadia Islam',
    instructorImage: '/Asset/sadia islam.jpg',
    level: 'Advanced',
    category: 'Web Development',
    modules: [
      { id: 1,
        title: 'MERN Overview',
        lectures: 4,
        duration: '2 hr',
        topics: [
          { id: 1, title: 'Stack intro', resources: [{ title: 'MERN overview', size: '200 KB', file: '/Asset/resources/mern/overview.pdf' }] },
          { id: 2, title: 'Project structure', resources: [{ title: 'Structure examples', size: '180 KB', file: '/Asset/resources/mern/structure.pdf' }] },
          { id: 3, title: 'Tooling', resources: [{ title: 'Tooling list', size: '120 KB', file: '/Asset/resources/mern/tooling.pdf' }] },
          { id: 4, title: 'Deployment options', resources: [{ title: 'Deploy options', size: '150 KB', file: '/Asset/resources/mern/deploy.pdf' }] },
        ] },
      { id: 2,
        title: 'React Frontend',
        lectures: 4,
        duration: '6 hr',
        topics: [
          { id: 1, title: 'Component model', resources: [{ title: 'Components guide', size: '200 KB', file: '/Asset/resources/mern/components.pdf' }] },
          { id: 2, title: 'State management', resources: [{ title: 'State patterns', size: '220 KB', file: '/Asset/resources/mern/state.pdf' }] },
          { id: 3, title: 'Routing', resources: [{ title: 'Routing examples', size: '130 KB', file: '/Asset/resources/mern/routing.pdf' }] },
          { id: 4, title: 'Forms & validation', resources: [{ title: 'Forms guide', size: '120 KB', file: '/Asset/resources/mern/forms.pdf' }] },
        ] },
      { id: 3,
        title: 'Node & Express Backend',
        lectures: 4,
        duration: '5 hr',
        topics: [
          { id: 1, title: 'API design', resources: [{ title: 'API design', size: '140 KB', file: '/Asset/resources/mern/api-design.pdf' }] },
          { id: 2, title: 'Database integration', resources: [{ title: 'DB integration', size: '160 KB', file: '/Asset/resources/mern/db-integration.pdf' }] },
          { id: 3, title: 'Auth & security', resources: [{ title: 'Auth guide', size: '150 KB', file: '/Asset/resources/mern/auth.pdf' }] },
          { id: 4, title: 'Testing backend', resources: [{ title: 'Backend tests', size: '130 KB', file: '/Asset/resources/mern/backend-tests.pdf' }] },
        ] },
      { id: 4,
        title: 'MongoDB & Deployment',
        lectures: 4,
        duration: '3.5 hr',
        topics: [
          { id: 1, title: 'Mongo basics', resources: [{ title: 'Mongo primer', size: '120 KB', file: '/Asset/resources/mern/mongo.pdf' }] },
          { id: 2, title: 'Indexes & performance', resources: [{ title: 'Indexes note', size: '110 KB', file: '/Asset/resources/mern/indexes.pdf' }] },
          { id: 3, title: 'Scaling', resources: [{ title: 'Scaling guide', size: '150 KB', file: '/Asset/resources/mern/scaling.pdf' }] },
          { id: 4, title: 'Deploy to cloud', resources: [{ title: 'Cloud deploy', size: '200 KB', file: '/Asset/resources/mern/cloud-deploy.pdf' }] },
        ] },
    ],
    whatYouWillLearn: [
      'Build React single-page applications',
      'Create REST APIs with Node & Express',
      'Persist data with MongoDB and deploy apps',
    ],
    resources: [
      { title: 'Project Starter', size: '5.2 MB', file: '/Asset/resources/mern-starter.zip' },
    ],
  },
];
